name:                lightblue
version:             0.2.1.1
description:         Please see the README on GitHub at <https://github.com/DaisukeBekki/lightblue#README.md>
homepage:            https://github.com/DaisukeBekki/lightblue
category:            CCG Parser, Higher-order Logic Prover
synopsis:            A Japanese CCG parser with DTS
license:             AllRightsReserved
license-file:        LICENSE
copyright:           Daisuke Bekki
author:              Daisuke Bekki and Bekki Laboratory
maintainer:          Daisuke Bekki
stability:           beta

extra-source-files:
  - README.md
  - ChangeLog.md
  - src/Parser/Japanese/Juman.dic
  - src/DTS/Alligator/AlexHappy/Lexer.x
  - src/DTS/Alligator/AlexHappy/Parser.y
  - src/DTS/Alligator/AlexHappy/Lexerf.x
  - src/DTS/Alligator/AlexHappy/Parserf.y
  - src/DTS/Alligator/AlexHappy/GetDepth/Lexer.x
  - src/DTS/Alligator/AlexHappy/GetDepth/Parser.y

dependencies:
  - base >= 4.8 && <5
  - containers >= 0.4
  - time >= 1.4
  - text >= 1.2
  - process >= 1.2
  - xml-conduit >= 1.3
  - optparse-applicative >= 0.13
  - semigroups >= 0.16
  - array >= 0.5.3.0
  - mtl >= 2.2.2
  - directory >=1.3.3.0
  - data-default
  - split
  - parsec >= 3.1
  - jsem >= 0.1.4
#  - hasktorch-tools >= 0.2

library:
  source-dirs: src
  default-extensions:
  - OverloadedStrings
  build-tools:
  - alex
  - happy
  exposed-modules:
  - Parser.ChartParser
  - Parser.CCG
  - Parser.Japanese.Lexicon
  - Parser.Japanese.CallJuman
  - Parser.Japanese.MyLexicon
  - Parser.Japanese.Templates
  - Interface
  - Interface.Text
  - Interface.TeX
  - Interface.XML
  - Interface.HTML
  - Interface.SVG
  - DTS.DTT
  - DTS.UDTTwithName
  - DTS.UDTT
  - DTS.Prover
  - DTS.Prover.Judgement
  - DTS.Prover.TypeChecker
  - DTS.DTStoProlog
  - DTS.Alligator.Arrowterm
  - DTS.Alligator.ProofTree
  - DTS.Alligator.AlexHappy.TPTPInfo
  - DTS.Alligator.AlexHappy.Eval
  - DTS.Alligator.AlexHappy.Lexer
  - DTS.Alligator.AlexHappy.Lexerf
  - DTS.Alligator.AlexHappy.Parser
  - DTS.Alligator.AlexHappy.Parserf
  - DTS.Alligator.AlexHappy.Syntax
  - DTS.Alligator.AlexHappy.Syntaxf
  - DTS.Alligator.AlexHappy.FileParser
  - DTS.Alligator.AlexHappy.Classification
  - DTS.Alligator.AlexHappy.GetDepth.Lexer
  - DTS.Alligator.AlexHappy.GetDepth.Parser
  - DTS.Alligator.AlexHappy.GetDepth.Syntax
  - DTS.Alligator.AlexHappy.GetDepth.Eval
  - DTS.Alligator.AlexHappy.GetDepth.FileParser
  - DTS.Alligator.Problem

executables:
  lightblue:
    source-dirs: app
    main: lightblueMain.hs
    ghc-options:  [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies: lightblue >= 0.2.1.0

tests:
  tptp:
    source-dirs: src/DTS/Alligator/AlexHappy
    main: TPTPTest.hs
    ghc-options:  [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies: lightblue >= 0.2.1.0

  tptp2pl:
    source-dirs: src/DTS/Alligator/AlexHappy
    main: TPTP2Prolog.hs
    ghc-options:  [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies: lightblue >= 0.2.1.0

  tptp2depth:
    source-dirs: src/DTS/Alligator/AlexHappy/GetDepth
    main: TPTPTest.hs
    ghc-options:  [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies: lightblue >= 0.2.1.0

  test:
    source-dirs: src/DTS/Alligator
    main: forTest.hs
    ghc-options:  [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies: lightblue >= 0.2.1.0
