name:         lightblue
version:      0.4.1
description:  Please see the README on GitHub at <https://github.com/DaisukeBekki/lightblue#README.md>
homepage:     https://github.com/DaisukeBekki/lightblue
category:     CCG Parser, Dependent Type Prover
synopsis:     A Japanese CCG parser with DTS
license:      AllRightsReserved
license-file: LICENSE
copyright:    Daisuke Bekki
author:       Daisuke Bekki and Bekki Laboratory
maintainer:   Daisuke Bekki
stability:    beta
ghc-options:  -Wall

extra-source-files:
  - README.md
  - ChangeLog.md
  - src/Parser/Language/Japanese/Juman/Juman.dic

dependencies:
  - base >= 4.8 && <5
  - containers >= 0.4
  - time >= 1.4
  - text >= 1.2
  - process >= 1.2
  - xml-conduit >= 1.9
  - optparse-applicative >= 0.13
  - semigroups >= 0.16
  - jsem >= 1.1
  - nlp-tools >= 0.2.0
  - array >= 0.5.3.0
  - mtl >= 2.2.2
  - directory >=1.3.3.0
  - data-default
  - split
  - aeson >= 1.0
  - bytestring >= 0.10
  - yaml >= 0.8.3
  - parsec >= 3.1.14
  - filepath >= 1.4
  - shelly >= 1.8.1
  - mtl >= 2.2.2
  - serialise >= 0.2.4
  - list-t >= 1.0.0.0
  - store >= 0.7.14
  - witherable >= 0.4
  - parserModules
  - unicode-show >= 0.1
  - parallel >= 3.2.2
  - yesod >= 1.6
  - yesod-core >= 1.6 && <1.7
  - yesod-static >= 1.6 && <1.7
  - yesod-form >= 1.6 && <1.8
  - classy-prelude >= 1.5 && <1.6
  - classy-prelude-conduit >=1.5 && <1.6
  - classy-prelude-yesod >=1.5 && <1.6
  - file-embed
  - template-haskell
  - warp
  - monad-logger >=0.3 && <0.4
  - shakespeare >=2.0 && <2.1
  - hjsmin >=0.1 && <0.3
  - case-insensitive
  - http-client-tls
  - wai
  - wai-extra
  - fast-logger


library:
  source-dirs: src
  default-extensions:
  - OverloadedStrings
  exposed-modules:
  - Parser.ChartParser
  - Parser.CCG
  - Parser.PartialParsing
  - Parser.Language
  - Parser.LangOptions
  - Parser.Language.Japanese.Lexicon
  - Parser.Language.Japanese.MyLexicon
  - Parser.Language.Japanese.Templates
  - Parser.Language.Japanese.Juman.CallJuman
  - Parser.Language.Japanese.Juman.Config
  - Parser.Language.Japanese.Juman.ParseJumanDic
  - Parser.Language.Japanese.Juman.ConvertJumanDic
  - Parser.Language.Japanese.Filter
  - Parser.Language.Japanese.Filter.KNPFilter
  - Parser.Language.Japanese.Filter.KWJAFilter
  - Parser.Language.English.Lexicon
  - Interface
  - Interface.Text
  - Interface.TeX
  - Interface.XML
  - Interface.HTML
  - Interface.SVG
  - Interface.Tree
  - DTS.Index
  - DTS.GeneralTypeQuery
  - DTS.UDTTdeBruijn
  - DTS.UDTTwithName
  - DTS.DTTdeBruijn
  - DTS.DTTwithName
  - DTS.QueryTypes
  - DTS.TypeChecker
  - DTS.NaturalLanguageInference
  - DTS.Prover.Wani.WaniBase
  - DTS.Prover.Wani.Forward
  - DTS.Prover.Wani.Backward
  - DTS.Prover.Wani.BackwardRules
  - DTS.Prover.Wani.BackwardWithRules
  - DTS.Prover.Wani.Arrowterm
  - DTS.Prover.Wani.Prove

executables:
  lightblue:
    source-dirs:  app
    main:         lightblueMain.hs
    ghc-options:  [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies: lightblue

tests:
  testJumanDicSettings:
    source-dirs:  test/Juman
    main:         testJumanDicSettings.hs
    ghc-options:  [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies: lightblue
  typeCheck:
    source-dirs:  test/DTS
    main:         testTypeChecker.hs
    ghc-options:  [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies: lightblue
