#!/bin/bash
# Install:
#   brew install graphviz
#   chmod 755 parsem
# Usage
#   ./parsem <sentence>
cd ${LIGHTBLUE}
echo $1 | stack run lightblue -- parse -s svg | dot -Tsvg > tmp.svg; qlmanage -p tmp.svg
