resolver: lts-18.28

flags: {}

extra-deps:
  - git: http://github.com/DaisukeBekki/JSeM.git
    commit: 9834b94f9fdf787903a5926003a8122c467d621f
  - git: http://github.com/DaisukeBekki/nlp-tools
    commit: 1bf4e582c603c823a89c3dfd1fba0ab4d3d8899a
#  - git: git@github.com:DaisukeBekki/hasktorch-tools.git
#    commit: 936928cdee27e179a5e3775d146046b107b0eba1

allow-newer: true

build:
  haddock: false
  haddock-arguments:
    haddock-args:
    - --odir=haddock
  open-haddocks: false
  haddock-internal: false
  haddock-hyperlink-source: true

