resolver: lts-22.43

flags: {}

extra-deps:
- git: http://github.com/DaisukeBekki/JSeM
  commit: c2cd39168e267007b4690dbf625329bac57a8185
- git: http://github.com/DaisukeBekki/nlp-tools
  commit: e4bd3783f4e872b8df29538d9219e41f40378363
# - inline-c-0.9.1.6
# - inline-c-cpp-0.4.0.0
- git: https://github.com/hasktorch/hasktorch.git
  commit: 931fcc76411a277c857388b3a1f51b7d7c1eef1a
  # 4e846fdcd89df5c7c6991cb9d6142007a6bb0a58
  subdirs:
    - hasktorch
    - libtorch-ffi
    - libtorch-ffi-helper
- git: git@github.com:DaisukeBekki/hasktorch-tools.git
  commit: 936928cdee27e179a5e3775d146046b107b0eba1
# parserModule
- git: https://github.com/morning85/parserModules.git
  commit: 899aae39b8c57866148fb3b19a4ac2f393ffaabd

ghc-options:
  libtorch-ffi: -optcxx-Wno-error=stringop-overflow

extra-include-dirs:
  - libtorch/include/torch/csrc/api/include
  - libtorch/include/torch/include
  - libtorch/include

extra-lib-dirs:
  - libtorch/lib

allow-newer: true

build:
  haddock: false
  haddock-arguments:
    haddock-args:
    - --odir=haddock
  open-haddocks: false
  haddock-internal: false
  haddock-hyperlink-source: true

