:- style_check(-singleton).

:-use_module(swi_alligator,[prove/2]).
:- op(500,xfx,:).
:- op(300,yfx,-).
:- op(400,xfy,=>).
:- op(400,xfy,&).
:- op(300,fy,~).
:- dynamic checktheorem/6.
writeResult(Logic,ID,Prediction,Gold,Fname) :-
format('~w&~w&~w&~w&~w~n', [Logic,ID,Prediction,Gold,Fname]).
evalyes(Logic,ID) :-
  checkTheorem(Logic,ID,Context,Theorem,Gold,Fname),
  ( prove(Context,_ : Theorem) -> writeResult(Logic,ID,yes,Gold,Fname)).
evalno(Logic,ID) :-
  checkTheorem(Logic,ID,Context,Theorem,Gold,Fname),
  ( prove(Context,_ : ( ~ (Theorem) ) ) -> writeResult(Logic,ID,no,Gold,Fname) ).
checkTheorem(syn , 378 , [ type:set ,z : (( ( type ) ) -> ( ( prop ) )) , h : (( ( type ) ) -> ( ( prop ) )) , g : (( ( type ) ) -> ( ( prop ) )) , f : (( ( type ) ) -> ( ( prop ) )) , y : (( ( type ) ) -> ( ( prop ) )) , bigX : (( ( type ) ) -> ( ( prop ) )) ] , ( ~( ( ~( ( ~( ( ~( ( ~( ( ~( ( ~( ( ~( ( ~( ( ~( ~( ( ~( ( ( f ) )-( ( ( y ) )-( ( bigX ) ) ) ) ) \/ ( ( ( ( g ) )-( ( ( y ) )-( ( bigX ) ) ) ) \/ ( ~( ( ( f ) )-( ( bigX ) ) ) ) ) ) ) ) & ( ( ( ( f ) )-( ( ( y ) )-( ( bigX ) ) ) ) \/ ( ( ( f ) )-( ( bigX ) ) ) ) ) ) & ( ( ~( ( ( g ) )-( ( ( y ) )-( ( bigX ) ) ) ) ) \/ ( ( ( f ) )-( ( bigX ) ) ) ) ) ) & ( ( ~( ( ( f ) )-( ( ( y ) )-( ( bigX ) ) ) ) ) \/ ( ( ( ( h ) )-( ( ( y ) )-( ( bigX ) ) ) ) \/ ( ~( ( ( g ) )-( ( bigX ) ) ) ) ) ) ) ) & ( ( ( ( f ) )-( ( ( y ) )-( ( bigX ) ) ) ) \/ ( ( ( g ) )-( ( bigX ) ) ) ) ) ) & ( ( ~( ( ( h ) )-( ( ( y ) )-( ( bigX ) ) ) ) ) \/ ( ( ( g ) )-( ( bigX ) ) ) ) ) ) & ( ( ( ( f ) )-( ( ( y ) )-( ( bigX ) ) ) ) \/ ( ( ( ( h ) )-( ( ( y ) )-( ( bigX ) ) ) ) \/ ( ~( ( ( h ) )-( ( bigX ) ) ) ) ) ) ) ) & ( ( ~( ( ( g ) )-( ( ( y ) )-( ( bigX ) ) ) ) ) \/ ( ( ( ( h ) )-( ( ( y ) )-( ( bigX ) ) ) ) \/ ( ~( ( ( h ) )-( ( bigX ) ) ) ) ) ) ) ) & ( ( ~( ( ( f ) )-( ( ( y ) )-( ( bigX ) ) ) ) ) \/ ( ( ( ( g ) )-( ( ( y ) )-( ( bigX ) ) ) ) \/ ( ( ( h ) )-( ( bigX ) ) ) ) ) ) ) & ( ( ~( ( ( h ) )-( ( ( y ) )-( ( bigX ) ) ) ) ) \/ ( ( ( h ) )-( ( bigX ) ) ) ) ) ) & ( ( ~( ( ( f ) )-( ( ( z ) )-( ( bigX ) ) ) ) ) \/ ( ( ~( ( ( g ) )-( ( ( z ) )-( ( bigX ) ) ) ) ) \/ ( ~( ( ( h ) )-( ( ( z ) )-( ( bigX ) ) ) ) ) ) ) , no , '../../TPTP-v7.3.0/Problems/SYN/SYN328-1.p').
checkTheorem(syn , 379 , [ type:set ,big_h : (( ( type ) ) -> ( ( prop ) )) , big_g : (( ( type ) ) -> ( ( prop ) )) , big_f : (( ( type ) ) -> ( ( prop ) )) ] , sigma(X:type,pi(Y:type,pi(Z:type,( ( ( ( ( ( big_f ) )-( ( bigY ) ) ) -> ( ( ( big_g ) )-( ( bigY ) ) ) ) -> ( ( ( big_f ) )-( ( bigX ) ) ) ) & ( ( ( ( big_f ) )-( ( bigX ) ) ) -> ( ( ( ( big_f ) )-( ( bigY ) ) ) -> ( ( ( big_g ) )-( ( bigY ) ) ) ) ) ) -> ( ( ( ( ( ( ( big_f ) )-( ( bigY ) ) ) -> ( ( ( big_h ) )-( ( bigY ) ) ) ) -> ( ( ( big_g ) )-( ( bigX ) ) ) ) & ( ( ( ( big_g ) )-( ( bigX ) ) ) -> ( ( ( ( big_f ) )-( ( bigY ) ) ) -> ( ( ( big_h ) )-( ( bigY ) ) ) ) ) ) -> ( ( ( ( ( ( ( ( big_f ) )-( ( bigY ) ) ) -> ( ( ( big_g ) )-( ( bigY ) ) ) ) -> ( ( ( big_h ) )-( ( bigY ) ) ) ) -> ( ( ( big_h ) )-( ( bigX ) ) ) ) & ( ( ( ( big_h ) )-( ( bigX ) ) ) -> ( ( ( ( ( big_f ) )-( ( bigY ) ) ) -> ( ( ( big_g ) )-( ( bigY ) ) ) ) -> ( ( ( big_h ) )-( ( bigY ) ) ) ) ) ) -> ( ( ( ( big_f ) )-( ( bigZ ) ) ) & ( ( ( ( big_g ) )-( ( bigZ ) ) ) & ( ( ( big_h ) )-( ( bigZ ) ) ) ) ) ) )))) , yes , '../../TPTP-v7.3.0/Problems/SYN/SYN328+1.p').
checkTheorem(syn , 380 , [ type:set ,z : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) , bigY : (( type )) , f : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) , bigX : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) ] , ( ~( ( ~( ( ~( ~( ( ( f ) )-( ( bigX ) )-( ( bigX ) ) ) ) ) & ( ( ( f ) )-( ( bigY ) )-( ( bigY ) ) ) ) ) & ( ( ( f ) )-( ( bigX ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) ) ) ) ) & ( ~( ( ( f ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) )-( ( bigY ) ) ) ) , unknown , '../../TPTP-v7.3.0/Problems/SYN/SYN329-1.p').
checkTheorem(syn , 381 , [ type:set ,big_f : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) ] , sigma(X:type,sigma(Y:type,pi(Z:type,( ( ( big_f ) )-( ( bigX ) )-( ( bigX ) ) ) -> ( ( ( ( big_f ) )-( ( bigY ) )-( ( bigY ) ) ) -> ( ( ( ( big_f ) )-( ( bigX ) )-( ( bigZ ) ) ) -> ( ( ( big_f ) )-( ( bigZ ) )-( ( bigY ) ) ) ) )))) , no , '../../TPTP-v7.3.0/Problems/SYN/SYN329+1.p').
checkTheorem(syn , 382 , [ type:set ,f : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) , z : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) , bigY : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) , bigX : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) ] , ( ~( ( ~( ( ~( ( ~( ( ~( ( ~( ( ~( ~( ( ( ( f ) )-( ( bigX ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) ) ) \/ ( ~( ( ( f ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) )-( ( bigY ) ) ) ) ) ) ) & ( ( ~( ( ( f ) )-( ( bigX ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) ) ) ) \/ ( ( ( f ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) )-( ( bigY ) ) ) ) ) ) & ( ( ( ( f ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) )-( ( bigY ) ) ) \/ ( ~( ( ( f ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) ) ) ) ) ) ) & ( ( ~( ( ( f ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) )-( ( bigY ) ) ) ) \/ ( ( ( f ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) ) ) ) ) ) & ( ( ( ( f ) )-( ( bigX ) )-( ( bigY ) ) ) \/ ( ~( ( ( f ) )-( ( bigY ) )-( ( bigX ) ) ) ) ) ) ) & ( ( ~( ( ( f ) )-( ( bigY ) )-( ( bigX ) ) ) ) \/ ( ( ( f ) )-( ( bigX ) )-( ( bigY ) ) ) ) ) ) & ( ( ( ( f ) )-( ( bigX ) )-( ( bigY ) ) ) \/ ( ( ( f ) )-( ( bigX ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) ) ) ) ) ) & ( ( ~( ( ( f ) )-( ( bigX ) )-( ( bigY ) ) ) ) \/ ( ~( ( ( f ) )-( ( bigX ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) ) ) ) ) , unknown , '../../TPTP-v7.3.0/Problems/SYN/SYN330-1.p').
checkTheorem(syn , 383 , [ type:set ,big_f : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) ] , sigma(X:type,sigma(Y:type,pi(Z:type,( ( ( ( ( big_f ) )-( ( bigX ) )-( ( bigZ ) ) ) -> ( ( ( big_f ) )-( ( bigZ ) )-( ( bigY ) ) ) ) & ( ( ( ( big_f ) )-( ( bigZ ) )-( ( bigY ) ) ) -> ( ( ( big_f ) )-( ( bigX ) )-( ( bigZ ) ) ) ) ) -> ( ( ( ( ( ( big_f ) )-( ( bigZ ) )-( ( bigY ) ) ) -> ( ( ( big_f ) )-( ( bigZ ) )-( ( bigZ ) ) ) ) & ( ( ( ( big_f ) )-( ( bigZ ) )-( ( bigZ ) ) ) -> ( ( ( big_f ) )-( ( bigZ ) )-( ( bigY ) ) ) ) ) -> ( ( ( ( ( ( big_f ) )-( ( bigX ) )-( ( bigY ) ) ) -> ( ( ( big_f ) )-( ( bigY ) )-( ( bigX ) ) ) ) & ( ( ( ( big_f ) )-( ( bigY ) )-( ( bigX ) ) ) -> ( ( ( big_f ) )-( ( bigX ) )-( ( bigY ) ) ) ) ) -> ( ( ( ( ( big_f ) )-( ( bigX ) )-( ( bigY ) ) ) -> ( ( ( big_f ) )-( ( bigX ) )-( ( bigZ ) ) ) ) & ( ( ( ( big_f ) )-( ( bigX ) )-( ( bigZ ) ) ) -> ( ( ( big_f ) )-( ( bigX ) )-( ( bigY ) ) ) ) ) ) )))) , no , '../../TPTP-v7.3.0/Problems/SYN/SYN330+1.p').
