:- style_check(-singleton).

:-use_module(swi_alligator,[prove/2]).
:- op(500,xfx,:).
:- op(300,yfx,-).
:- op(400,xfy,=>).
:- op(400,xfy,&).
:- op(300,fy,~).
:- dynamic checktheorem/6.
writeResult(Logic,ID,Prediction,Gold,Fname) :-
format('~w&~w&~w&~w&~w~n', [Logic,ID,Prediction,Gold,Fname]).
evalyes(Logic,ID) :-
  checkTheorem(Logic,ID,Context,Theorem,Gold,Fname),
  ( prove(Context,_ : Theorem) -> writeResult(Logic,ID,yes,Gold,Fname)).
evalno(Logic,ID) :-
  checkTheorem(Logic,ID,Context,Theorem,Gold,Fname),
  ( prove(Context,_ : ( ~ (Theorem) ) ) -> writeResult(Logic,ID,no,Gold,Fname) ).
checkTheorem(syn , 930 , [ type:set ,sk4 : (( type )) , sk3 : (( type )) , sk2 : (( type )) , sk1 : (( type )) , q : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) , bigB : (( type )) , p : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) , bigC : (( type )) , bigA : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) ] , ( ~( ( ~( ( ~( ( ~( ( ~( ~( ( ( ( p ) )-( ( bigA ) )-( ( bigC ) ) ) \/ ( ( ~( ( ( p ) )-( ( bigA ) )-( ( bigB ) ) ) ) \/ ( ~( ( ( p ) )-( ( bigB ) )-( ( bigC ) ) ) ) ) ) ) ) & ( ( ( ( q ) )-( ( bigA ) )-( ( bigC ) ) ) \/ ( ( ~( ( ( q ) )-( ( bigA ) )-( ( bigB ) ) ) ) \/ ( ~( ( ( q ) )-( ( bigB ) )-( ( bigC ) ) ) ) ) ) ) ) & ( ( ( ( q ) )-( ( bigB ) )-( ( bigA ) ) ) \/ ( ~( ( ( q ) )-( ( bigA ) )-( ( bigB ) ) ) ) ) ) ) & ( ( ( ( p ) )-( ( bigA ) )-( ( bigB ) ) ) \/ ( ( ( q ) )-( ( bigA ) )-( ( bigB ) ) ) ) ) ) & ( ~( ( ( p ) )-( ( sk1 ) )-( ( sk2 ) ) ) ) ) ) & ( ~( ( ( q ) )-( ( sk3 ) )-( ( sk4 ) ) ) ) , no , '../../TPTP-v7.3.0/Problems/SYN/SYN726-1.p').
checkTheorem(syn , 931 , [ type:set ,q : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) , p : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) ] , ( ( ( pi(X:type,pi(Y:type,pi(Z:type,( ( ( ( p ) )-( ( bigX ) )-( ( bigY ) ) ) & ( ( ( p ) )-( ( bigY ) )-( ( bigZ ) ) ) ) -> ( ( ( p ) )-( ( bigX ) )-( ( bigZ ) ) )))) ) & ( ( pi(X:type,pi(Y:type,pi(Z:type,( ( ( ( q ) )-( ( bigX ) )-( ( bigY ) ) ) & ( ( ( q ) )-( ( bigY ) )-( ( bigZ ) ) ) ) -> ( ( ( q ) )-( ( bigX ) )-( ( bigZ ) ) )))) ) & ( ( pi(X:type,pi(Y:type,( ( ( q ) )-( ( bigX ) )-( ( bigY ) ) ) -> ( ( ( q ) )-( ( bigY ) )-( ( bigX ) ) ))) ) & ( pi(X:type,pi(Y:type,( ( ( p ) )-( ( bigX ) )-( ( bigY ) ) ) \/ ( ( ( q ) )-( ( bigX ) )-( ( bigY ) ) ))) ) ) ) ) -> ( pi(X:type,pi(Y:type,( ( p ) )-( ( bigX ) )-( ( bigY ) ))) ) ) \/ ( pi(X:type,pi(Y:type,( ( q ) )-( ( bigX ) )-( ( bigY ) ))) ) , yes , '../../TPTP-v7.3.0/Problems/SYN/SYN726+1.p').
checkTheorem(syn , 932 , [ type:set ,sk1 : (( ( type ) ) -> ( ( prop ) )) , bigB : (( type )) , lyle : (( type )) , likes : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) , bruce : (( type )) , bigA : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) ] , ( ~( ( ~( ~( ( ( likes ) )-( ( bigA ) )-( ( bruce ) ) ) ) ) & ( ( ( ( likes ) )-( ( lyle ) )-( ( bigA ) ) ) \/ ( ~( ( ( likes ) )-( ( bigA ) )-( ( bigB ) ) ) ) ) ) ) & ( ~( ( ( likes ) )-( ( bigA ) )-( ( ( sk1 ) )-( ( bigA ) ) ) ) ) , no , '../../TPTP-v7.3.0/Problems/SYN/SYN727-1.p').
checkTheorem(syn , 933 , [ type:set ,lyle : (( type )) , likes : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) , bruce : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) ] , ( ( pi(X:type,( ( likes ) )-( ( bigX ) )-( ( bruce ) )) ) & ( pi(Y:type,( sigma(Z:type,( ( likes ) )-( ( bigY ) )-( ( bigZ ) )) ) -> ( ( ( likes ) )-( ( lyle ) )-( ( bigY ) ) )) ) ) -> ( sigma(U:type,pi(V:type,( ( likes ) )-( ( bigU ) )-( ( bigV ) ))) ) , yes , '../../TPTP-v7.3.0/Problems/SYN/SYN727+1.p').
checkTheorem(syn , 934 , [ type:set ,sk2 : (( type )) , g : (( ( type ) ) -> ( ( prop ) )) , q : (( ( type ) ) -> ( ( prop ) )) , f : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) , sk1 : (( ( type ) ) -> ( ( prop ) )) , m : (( ( type ) ) -> ( ( prop ) )) , bigB : (( type )) , bigA : (( type )) , p : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) , bigC : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) ] , ( ~( ( ~( ( ~( ( ~( ~( ( ( ( p ) )-( ( bigC ) )-( ( bigC ) ) ) \/ ( ~( ( ( p ) )-( ( bigA ) )-( ( bigB ) ) ) ) ) ) ) & ( ( ( ( m ) )-( ( bigA ) ) ) \/ ( ( ( p ) )-( ( bigA ) )-( ( ( sk1 ) )-( ( bigA ) ) ) ) ) ) ) & ( ( ( ( q ) )-( ( ( f ) )-( ( bigA ) )-( ( ( sk1 ) )-( ( bigA ) ) ) ) ) \/ ( ( ( p ) )-( ( bigA ) )-( ( ( sk1 ) )-( ( bigA ) ) ) ) ) ) ) & ( ( ~( ( ( m ) )-( ( ( g ) )-( ( bigA ) ) ) ) ) \/ ( ~( ( ( q ) )-( ( bigA ) ) ) ) ) ) ) & ( ( ~( ( ( p ) )-( ( sk2 ) )-( ( sk2 ) ) ) ) \/ ( ~( ( ( p ) )-( ( ( g ) )-( ( sk2 ) ) )-( ( bigA ) ) ) ) ) , no , '../../TPTP-v7.3.0/Problems/SYN/SYN728-1.p').
checkTheorem(syn , 935 , [ type:set ,g : (( ( type ) ) -> ( ( prop ) )) , q : (( ( type ) ) -> ( ( prop ) )) , f : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) , m : (( ( type ) ) -> ( ( prop ) )) , p : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) ] , ( ( pi(X:type,( sigma(Y:type,( ( p ) )-( ( bigX ) )-( ( bigY ) )) ) -> ( pi(Z:type,( ( p ) )-( ( bigZ ) )-( ( bigZ ) )) )) ) & ( ( pi(R:type,sigma(S:type,( ( ( p ) )-( ( bigR ) )-( ( bigS ) ) ) \/ ( ( ( ( m ) )-( ( bigR ) ) ) & ( ( ( q ) )-( ( ( f ) )-( ( bigR ) )-( ( bigS ) ) ) ) ))) ) & ( pi(W:type,( ( ( q ) )-( ( bigW ) ) ) -> ( ~( ( ( m ) )-( ( ( g ) )-( ( bigW ) ) ) ) )) ) ) ) -> ( pi(U:type,sigma(V:type,( ( ( p ) )-( ( ( g ) )-( ( bigU ) ) )-( ( bigV ) ) ) & ( ( ( p ) )-( ( bigU ) )-( ( bigU ) ) ))) ) , yes , '../../TPTP-v7.3.0/Problems/SYN/SYN728+1.p').
