:- style_check(-singleton).

:-use_module(swi_alligator,[prove/2]).
:- op(500,xfx,:).
:- op(300,yfx,-).
:- op(400,xfy,=>).
:- op(400,xfy,&).
:- op(300,fy,~).
:- dynamic checktheorem/6.
writeResult(Logic,ID,Prediction,Gold,Fname) :-
format('~w&~w&~w&~w&~w~n', [Logic,ID,Prediction,Gold,Fname]).
evalyes(Logic,ID) :-
  checkTheorem(Logic,ID,Context,Theorem,Gold,Fname),
  ( prove(Context,_ : Theorem) -> writeResult(Logic,ID,yes,Gold,Fname)).
evalno(Logic,ID) :-
  checkTheorem(Logic,ID,Context,Theorem,Gold,Fname),
  ( prove(Context,_ : ( ~ (Theorem) ) ) -> writeResult(Logic,ID,no,Gold,Fname) ).
checkTheorem(syn , 384 , [ type:set ,f : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) , z : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) , bigY : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) , bigX : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) ] , ( ~( ( ~( ( ~( ( ~( ( ~( ( ~( ~( ( ( f ) )-( ( bigX ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) ) ) ) ) & ( ( ( f ) )-( ( bigY ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) ) ) ) ) & ( ( ( ( f ) )-( ( bigX ) )-( ( bigY ) ) ) \/ ( ~( ( ( f ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) ) ) ) ) ) ) & ( ( ~( ( ( f ) )-( ( bigX ) )-( ( bigY ) ) ) ) \/ ( ( ( f ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) ) ) ) ) ) & ( ( ( ( f ) )-( ( bigY ) )-( ( bigX ) ) ) \/ ( ( ( f ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) ) ) ) ) ) & ( ~( ( ( f ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) )-( ( bigX ) ) ) ) ) ) & ( ~( ( ( f ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) )-( ( bigY ) ) ) ) , no , '../../TPTP-v7.3.0/Problems/SYN/SYN331-1.p').
checkTheorem(syn , 385 , [ type:set ,big_f : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) ] , sigma(X:type,sigma(Y:type,pi(Z:type,( ( ( big_f ) )-( ( bigX ) )-( ( bigZ ) ) ) -> ( ( ( ( big_f ) )-( ( bigY ) )-( ( bigZ ) ) ) -> ( ( ( ( ( ( big_f ) )-( ( bigX ) )-( ( bigY ) ) ) -> ( ( ( big_f ) )-( ( bigZ ) )-( ( bigZ ) ) ) ) & ( ( ( ( big_f ) )-( ( bigZ ) )-( ( bigZ ) ) ) -> ( ( ( big_f ) )-( ( bigX ) )-( ( bigY ) ) ) ) ) -> ( ( ( ( ( big_f ) )-( ( bigY ) )-( ( bigX ) ) ) \/ ( ( ( big_f ) )-( ( bigZ ) )-( ( bigZ ) ) ) ) -> ( ( ( ( big_f ) )-( ( bigZ ) )-( ( bigX ) ) ) \/ ( ( ( big_f ) )-( ( bigZ ) )-( ( bigY ) ) ) ) ) ) )))) , yes , '../../TPTP-v7.3.0/Problems/SYN/SYN331+1.p').
checkTheorem(syn , 386 , [ type:set ,z : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) , f : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) , bigY : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) , bigX : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) ] , ( ~( ( ~( ( ~( ( ~( ( ~( ( ~( ( ~( ( ~( ( ~( ( ~( ( ~( ( ~( ( ~( ~( ( ( ( f ) )-( ( bigX ) )-( ( bigY ) ) ) \/ ( ( ( f ) )-( ( bigX ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) ) ) ) ) ) & ( ( ( ( f ) )-( ( bigY ) )-( ( bigX ) ) ) \/ ( ( ( f ) )-( ( bigX ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) ) ) ) ) ) & ( ( ~( ( ( f ) )-( ( bigX ) )-( ( bigY ) ) ) ) \/ ( ( ~( ( ( f ) )-( ( bigY ) )-( ( bigX ) ) ) ) \/ ( ~( ( ( f ) )-( ( bigX ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) ) ) ) ) ) ) ) & ( ( ( ( f ) )-( ( bigX ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) ) ) \/ ( ~( ( ( f ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) )-( ( bigX ) ) ) ) ) ) ) & ( ( ~( ( ( f ) )-( ( bigX ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) ) ) ) \/ ( ( ( f ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) )-( ( bigX ) ) ) ) ) ) & ( ( ( ( f ) )-( ( bigX ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) ) ) \/ ( ~( ( ( f ) )-( ( bigY ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) ) ) ) ) ) ) & ( ( ~( ( ( f ) )-( ( bigX ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) ) ) ) \/ ( ( ( f ) )-( ( bigY ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) ) ) ) ) ) & ( ( ~( ( ( f ) )-( ( bigY ) )-( ( bigX ) ) ) ) \/ ( ( ( ( f ) )-( ( bigX ) )-( ( bigY ) ) ) \/ ( ~( ( ( f ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) ) ) ) ) ) ) ) & ( ( ( ( f ) )-( ( bigY ) )-( ( bigX ) ) ) \/ ( ( ( f ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) ) ) ) ) ) & ( ( ~( ( ( f ) )-( ( bigX ) )-( ( bigY ) ) ) ) \/ ( ( ( f ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) ) ) ) ) ) & ( ( ( ( f ) )-( ( bigX ) )-( ( bigY ) ) ) \/ ( ( ~( ( ( f ) )-( ( bigY ) )-( ( bigX ) ) ) ) \/ ( ( ( f ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) )-( ( bigY ) ) ) ) ) ) ) & ( ( ~( ( ( f ) )-( ( bigX ) )-( ( bigY ) ) ) ) \/ ( ( ( ( f ) )-( ( bigY ) )-( ( bigX ) ) ) \/ ( ( ( f ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) )-( ( bigY ) ) ) ) ) ) ) & ( ( ( ( f ) )-( ( bigX ) )-( ( bigY ) ) ) \/ ( ( ( ( f ) )-( ( bigY ) )-( ( bigX ) ) ) \/ ( ~( ( ( f ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) )-( ( bigY ) ) ) ) ) ) ) ) & ( ( ~( ( ( f ) )-( ( bigX ) )-( ( bigY ) ) ) ) \/ ( ( ~( ( ( f ) )-( ( bigY ) )-( ( bigX ) ) ) ) \/ ( ~( ( ( f ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) )-( ( bigY ) ) ) ) ) ) , no , '../../TPTP-v7.3.0/Problems/SYN/SYN332-1.p').
checkTheorem(syn , 387 , [ type:set ,big_f : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) ] , sigma(X:type,sigma(Y:type,pi(Z:type,( ( ( ( ( ( big_f ) )-( ( bigX ) )-( ( bigY ) ) ) & ( ( ( big_f ) )-( ( bigY ) )-( ( bigX ) ) ) ) -> ( ( ( big_f ) )-( ( bigX ) )-( ( bigZ ) ) ) ) & ( ( ( ( big_f ) )-( ( bigX ) )-( ( bigZ ) ) ) -> ( ( ( ( big_f ) )-( ( bigX ) )-( ( bigY ) ) ) & ( ( ( big_f ) )-( ( bigY ) )-( ( bigX ) ) ) ) ) ) -> ( ( ( ( ( ( big_f ) )-( ( bigX ) )-( ( bigZ ) ) ) -> ( ( ( big_f ) )-( ( bigZ ) )-( ( bigX ) ) ) ) & ( ( ( ( big_f ) )-( ( bigZ ) )-( ( bigX ) ) ) -> ( ( ( big_f ) )-( ( bigX ) )-( ( bigZ ) ) ) ) ) -> ( ( ( ( ( ( big_f ) )-( ( bigX ) )-( ( bigZ ) ) ) -> ( ( ( big_f ) )-( ( bigY ) )-( ( bigZ ) ) ) ) & ( ( ( ( big_f ) )-( ( bigY ) )-( ( bigZ ) ) ) -> ( ( ( big_f ) )-( ( bigX ) )-( ( bigZ ) ) ) ) ) -> ( ( ( ( ( ( ( big_f ) )-( ( bigY ) )-( ( bigX ) ) ) -> ( ( ( big_f ) )-( ( bigX ) )-( ( bigY ) ) ) ) -> ( ( ( big_f ) )-( ( bigZ ) )-( ( bigZ ) ) ) ) & ( ( ( ( big_f ) )-( ( bigZ ) )-( ( bigZ ) ) ) -> ( ( ( ( big_f ) )-( ( bigY ) )-( ( bigX ) ) ) -> ( ( ( big_f ) )-( ( bigX ) )-( ( bigY ) ) ) ) ) ) -> ( ( ( ( ( ( ( big_f ) )-( ( bigX ) )-( ( bigY ) ) ) -> ( ( ( big_f ) )-( ( bigY ) )-( ( bigX ) ) ) ) & ( ( ( ( big_f ) )-( ( bigY ) )-( ( bigX ) ) ) -> ( ( ( big_f ) )-( ( bigX ) )-( ( bigY ) ) ) ) ) -> ( ( ( big_f ) )-( ( bigZ ) )-( ( bigY ) ) ) ) & ( ( ( ( big_f ) )-( ( bigZ ) )-( ( bigY ) ) ) -> ( ( ( ( ( big_f ) )-( ( bigX ) )-( ( bigY ) ) ) -> ( ( ( big_f ) )-( ( bigY ) )-( ( bigX ) ) ) ) & ( ( ( ( big_f ) )-( ( bigY ) )-( ( bigX ) ) ) -> ( ( ( big_f ) )-( ( bigX ) )-( ( bigY ) ) ) ) ) ) ) ) ) )))) , yes , '../../TPTP-v7.3.0/Problems/SYN/SYN332+1.p').
checkTheorem(syn , 388 , [ type:set ,g : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) , z : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) , f : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) , bigY : (( type )) , bigX : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) ] , ( ~( ( ~( ~( ( ( f ) )-( ( bigX ) )-( ( bigY ) ) ) ) ) & ( ( ~( ( ( f ) )-( ( bigY ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) ) ) ) \/ ( ( ~( ( ( f ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) ) ) ) \/ ( ( ( g ) )-( ( bigX ) )-( ( bigY ) ) ) ) ) ) ) & ( ( ~( ( ( f ) )-( ( bigY ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) ) ) ) \/ ( ( ~( ( ( f ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) ) ) ) \/ ( ( ~( ( ( g ) )-( ( bigX ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) ) ) ) \/ ( ~( ( ( g ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) ) ) ) ) ) ) , no , '../../TPTP-v7.3.0/Problems/SYN/SYN333-1.p').
checkTheorem(syn , 389 , [ type:set ,big_g : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) , big_f : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) ] , sigma(X:type,sigma(Y:type,pi(Z:type,( ( ( big_f ) )-( ( bigX ) )-( ( bigY ) ) ) -> ( ( ( ( big_f ) )-( ( bigY ) )-( ( bigZ ) ) ) & ( ( ( ( big_f ) )-( ( bigZ ) )-( ( bigZ ) ) ) & ( ( ( ( ( big_f ) )-( ( bigX ) )-( ( bigY ) ) ) & ( ( ( big_g ) )-( ( bigX ) )-( ( bigY ) ) ) ) -> ( ( ( ( big_g ) )-( ( bigX ) )-( ( bigZ ) ) ) & ( ( ( big_g ) )-( ( bigZ ) )-( ( bigZ ) ) ) ) ) ) )))) , yes , '../../TPTP-v7.3.0/Problems/SYN/SYN333+1.p').
