:- style_check(-singleton).

:-use_module(swi_alligator,[prove/2]).
:- op(500,xfx,:).
:- op(300,yfx,-).
:- op(400,xfy,=>).
:- op(400,xfy,&).
:- op(300,fy,~).
:- dynamic checktheorem/6.
writeResult(Logic,ID,Prediction,Gold,Fname) :-
format('~w&~w&~w&~w&~w~n', [Logic,ID,Prediction,Gold,Fname]).
evalyes(Logic,ID) :-
  checkTheorem(Logic,ID,Context,Theorem,Gold,Fname),
  ( prove(Context,_ : Theorem) -> writeResult(Logic,ID,yes,Gold,Fname)).
evalno(Logic,ID) :-
  checkTheorem(Logic,ID,Context,Theorem,Gold,Fname),
  ( prove(Context,_ : ( ~ (Theorem) ) ) -> writeResult(Logic,ID,no,Gold,Fname) ).
checkTheorem(syn , 348 , [ type:set ,d : (( type )) , c : (( type )) , b : (( type )) , a : (( type )) , f : (( ( type ) ) -> ( ( prop ) )) , g : (( ( type ) ) -> ( ( prop ) )) , p : (( ( type ) ) -> ( ( ( type ) ) -> ( ( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) ) ) )) , bigX2 : (( type )) , bigX1 : (( type )) , bigX : (( type )) , bigX3 : (( ( type ) ) -> ( ( ( type ) ) -> ( ( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) ) ) )) ] , ( ~( ( ~( ( ~( ( ~( ( ~( ~( ( ( ( p ) )-( ( bigX3 ) )-( ( bigX ) )-( ( bigX1 ) )-( ( bigX2 ) ) ) \/ ( ~( ( ( p ) )-( ( bigX ) )-( ( bigX1 ) )-( ( bigX2 ) )-( ( bigX3 ) ) ) ) ) ) ) & ( ( ( ( p ) )-( ( bigX3 ) )-( ( bigX2 ) )-( ( bigX1 ) )-( ( bigX ) ) ) \/ ( ~( ( ( p ) )-( ( bigX ) )-( ( bigX1 ) )-( ( bigX2 ) )-( ( bigX3 ) ) ) ) ) ) ) & ( ( ( ( p ) )-( ( bigX ) )-( ( bigX1 ) )-( ( bigX2 ) )-( ( ( g ) )-( ( bigX3 ) ) ) ) \/ ( ~( ( ( p ) )-( ( bigX ) )-( ( bigX1 ) )-( ( bigX2 ) )-( ( bigX3 ) ) ) ) ) ) ) & ( ( ( ( p ) )-( ( ( f ) )-( ( bigX ) ) )-( ( bigX1 ) )-( ( bigX2 ) )-( ( bigX3 ) ) ) \/ ( ~( ( ( p ) )-( ( bigX ) )-( ( bigX1 ) )-( ( bigX2 ) )-( ( bigX3 ) ) ) ) ) ) ) & ( ( ( p ) )-( ( a ) )-( ( b ) )-( ( c ) )-( ( d ) ) ) ) ) & ( ~( ( ( p ) )-( ( ( f ) )-( ( ( g ) )-( ( d ) ) ) )-( ( ( f ) )-( ( ( g ) )-( ( c ) ) ) )-( ( ( f ) )-( ( ( g ) )-( ( b ) ) ) )-( ( ( f ) )-( ( ( g ) )-( ( a ) ) ) ) ) ) , no , '../../TPTP-v7.3.0/Problems/SYN/SYN311-1.p').
checkTheorem(syn , 349 , [ type:set ,d : (( type )) , c : (( type )) , b : (( type )) , a : (( type )) , g : (( ( type ) ) -> ( ( prop ) )) , f : (( ( type ) ) -> ( ( prop ) )) , bigX1 : (( type )) , p : (( ( type ) ) -> ( ( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) ) )) , bigX2 : (( type )) , bigX3 : (( type )) , bigX : (( ( type ) ) -> ( ( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) ) )) ] , ( ~( ( ~( ( ~( ( ~( ( ~( ( ~( ( ~( ~( ( ( ( p ) )-( ( bigX ) )-( ( bigX3 ) )-( ( bigX2 ) ) ) \/ ( ( ~( ( ( p ) )-( ( bigX ) )-( ( bigX1 ) )-( ( bigX2 ) ) ) ) \/ ( ~( ( ( p ) )-( ( bigX1 ) )-( ( bigX3 ) )-( ( bigX2 ) ) ) ) ) ) ) ) & ( ( ( ( p ) )-( ( bigX2 ) )-( ( bigX1 ) )-( ( bigX ) ) ) \/ ( ~( ( ( p ) )-( ( bigX ) )-( ( bigX1 ) )-( ( bigX2 ) ) ) ) ) ) ) & ( ( ( ( p ) )-( ( bigX1 ) )-( ( bigX ) )-( ( bigX2 ) ) ) \/ ( ~( ( ( p ) )-( ( bigX ) )-( ( bigX1 ) )-( ( bigX2 ) ) ) ) ) ) ) & ( ( ( ( p ) )-( ( bigX ) )-( ( bigX1 ) )-( ( ( f ) )-( ( bigX2 ) ) ) ) \/ ( ~( ( ( p ) )-( ( bigX ) )-( ( bigX1 ) )-( ( bigX2 ) ) ) ) ) ) ) & ( ( ( ( p ) )-( ( ( g ) )-( ( bigX ) ) )-( ( bigX1 ) )-( ( bigX2 ) ) ) \/ ( ~( ( ( p ) )-( ( bigX ) )-( ( bigX1 ) )-( ( bigX2 ) ) ) ) ) ) ) & ( ( ( p ) )-( ( a ) )-( ( ( f ) )-( ( b ) ) )-( ( c ) ) ) ) ) & ( ( ( p ) )-( ( ( f ) )-( ( b ) ) )-( ( d ) )-( ( c ) ) ) ) ) & ( ~( ( ( p ) )-( ( ( f ) )-( ( ( g ) )-( ( a ) ) ) )-( ( ( f ) )-( ( ( g ) )-( ( d ) ) ) )-( ( ( f ) )-( ( ( g ) )-( ( c ) ) ) ) ) ) , no , '../../TPTP-v7.3.0/Problems/SYN/SYN312-1.p').
checkTheorem(syn , 350 , [ type:set ,j2 : (( ( type ) ) -> ( ( prop ) )) , h2 : (( ( type ) ) -> ( ( prop ) )) , j1 : (( ( type ) ) -> ( ( prop ) )) , bigY1 : (( type )) , h1 : (( ( type ) ) -> ( ( prop ) )) , j0 : (( ( type ) ) -> ( ( prop ) )) , bigY2 : (( ( type ) ) -> ( ( prop ) )) , bigY0 : (( ( type ) ) -> ( ( prop ) )) , h0 : (( ( type ) ) -> ( ( prop ) )) , bigX2 : (( type )) , f1 : (( ( type ) ) -> ( ( prop ) )) , p : (( ( type ) ) -> ( ( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) ) )) , bigX1 : (( ( type ) ) -> ( ( prop ) )) , f0 : (( ( type ) ) -> ( ( prop ) )) , bigX0 : (( ( type ) ) -> ( ( prop ) )) ] , ( ~( ~( ( ~( ( ( p ) )-( ( bigX0 ) )-( ( ( f0 ) )-( ( bigX0 ) ) )-( ( bigX1 ) ) ) ) \/ ( ~( ( ( p ) )-( ( bigX0 ) )-( ( ( f1 ) )-( ( bigX1 ) ) )-( ( bigX2 ) ) ) ) ) ) ) & ( ( ( ( p ) )-( ( h0 ) )-( ( bigY0 ) )-( ( ( j0 ) )-( ( bigY2 ) ) ) ) \/ ( ( ( ( p ) )-( ( ( h1 ) )-( ( bigY0 ) ) )-( ( bigY1 ) )-( ( ( j1 ) )-( ( bigY2 ) ) ) ) \/ ( ( ( p ) )-( ( ( h2 ) )-( ( bigY1 ) ) )-( ( bigY2 ) )-( ( ( j2 ) )-( ( bigY2 ) ) ) ) ) ) , no , '../../TPTP-v7.3.0/Problems/SYN/SYN313-1.001.002.p').
checkTheorem(syn , 351 , [ type:set ,bigY3 : (( type )) , j1 : (( ( type ) ) -> ( ( prop ) )) , h1 : (( ( type ) ) -> ( ( prop ) )) , bigY2 : (( type )) , j0 : (( ( type ) ) -> ( ( prop ) )) , bigY1 : (( ( type ) ) -> ( ( prop ) )) , bigY0 : (( ( type ) ) -> ( ( prop ) )) , h0 : (( ( type ) ) -> ( ( prop ) )) , g2 : (( ( type ) ) -> ( ( prop ) )) , f2 : (( ( type ) ) -> ( ( prop ) )) , g1 : (( ( type ) ) -> ( ( prop ) )) , bigX2 : (( type )) , f1 : (( ( type ) ) -> ( ( prop ) )) , p : (( ( type ) ) -> ( ( ( type ) ) -> ( ( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) ) ) )) , g0 : (( ( type ) ) -> ( ( prop ) )) , bigX3 : (( ( type ) ) -> ( ( prop ) )) , bigX1 : (( ( type ) ) -> ( ( ( type ) ) -> ( ( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) ) ) )) , f0 : (( ( type ) ) -> ( ( prop ) )) , bigX0 : (( ( type ) ) -> ( ( prop ) )) ] , ( ~( ~( ( ( ( p ) )-( ( bigX0 ) )-( ( ( f0 ) )-( ( bigX0 ) ) )-( ( bigX1 ) )-( ( ( g0 ) )-( ( bigX3 ) ) ) ) \/ ( ( ( ( p ) )-( ( bigX0 ) )-( ( ( f1 ) )-( ( bigX1 ) ) )-( ( bigX2 ) )-( ( ( g1 ) )-( ( bigX3 ) ) ) ) \/ ( ( ( p ) )-( ( bigX0 ) )-( ( ( f2 ) )-( ( bigX2 ) ) )-( ( bigX3 ) )-( ( ( g2 ) )-( ( bigX3 ) ) ) ) ) ) ) ) & ( ( ~( ( ( p ) )-( ( h0 ) )-( ( bigY0 ) )-( ( ( j0 ) )-( ( bigY1 ) ) )-( ( bigY2 ) ) ) ) \/ ( ~( ( ( p ) )-( ( ( h1 ) )-( ( bigY0 ) ) )-( ( bigY1 ) )-( ( ( j1 ) )-( ( bigY2 ) ) )-( ( bigY3 ) ) ) ) ) , no , '../../TPTP-v7.3.0/Problems/SYN/SYN314-1.002.001.p').
checkTheorem(syn , 352 , [ type:set ,y : (( ( type ) ) -> ( ( prop ) )) , p : (( ( type ) ) -> ( ( prop ) )) , a : (( type )) , f : (( ( type ) ) -> ( ( prop ) )) , bigX : (( ( type ) ) -> ( ( prop ) )) ] , ( ~( ( ~( ( ~( ~( ( ~( ( ( f ) )-( ( bigX ) ) ) ) \/ ( ( ( p ) )-( ( a ) ) ) ) ) ) & ( ( ~( ( ( p ) )-( ( a ) ) ) ) \/ ( ( ( f ) )-( ( bigX ) ) ) ) ) ) & ( ( ~( ( ( f ) )-( ( ( y ) )-( ( bigX ) ) ) ) ) \/ ( ~( ( ( p ) )-( ( a ) ) ) ) ) ) ) & ( ( ( ( p ) )-( ( a ) ) ) \/ ( ( ( f ) )-( ( ( y ) )-( ( bigX ) ) ) ) ) , no , '../../TPTP-v7.3.0/Problems/SYN/SYN315-1.p').
checkTheorem(syn , 353 , [ type:set ,p : (( type )) , big_f : (( ( type ) ) -> ( ( prop ) )) ] , sigma(X:type,pi(Y:type,( ( ( ( ( big_f ) )-( ( bigX ) ) ) -> ( ( p ) ) ) & ( ( ( p ) ) -> ( ( ( big_f ) )-( ( bigX ) ) ) ) ) -> ( ( ( ( ( big_f ) )-( ( bigY ) ) ) -> ( ( p ) ) ) & ( ( ( p ) ) -> ( ( ( big_f ) )-( ( bigY ) ) ) ) ))) , yes , '../../TPTP-v7.3.0/Problems/SYN/SYN315+1.p').
