:- style_check(-singleton).

:-use_module(swi_alligator,[prove/2]).
:- op(500,xfx,:).
:- op(300,yfx,-).
:- op(400,xfy,=>).
:- op(400,xfy,&).
:- op(300,fy,~).
:- dynamic checktheorem/6.
writeResult(Logic,ID,Prediction,Gold,Fname) :-
format('~w&~w&~w&~w&~w~n', [Logic,ID,Prediction,Gold,Fname]).
evalyes(Logic,ID) :-
  checkTheorem(Logic,ID,Context,Theorem,Gold,Fname),
  ( prove(Context,_ : Theorem) -> writeResult(Logic,ID,yes,Gold,Fname)).
evalno(Logic,ID) :-
  checkTheorem(Logic,ID,Context,Theorem,Gold,Fname),
  ( prove(Context,_ : ( ~ (Theorem) ) ) -> writeResult(Logic,ID,no,Gold,Fname) ).
checkTheorem(syn , 72 , [ type:set ,big_j : (( ( type ) ) -> ( ( prop ) )) , big_h : (( ( type ) ) -> ( ( prop ) )) , big_g : (( ( type ) ) -> ( ( prop ) )) , big_f : (( ( type ) ) -> ( ( prop ) )) , axiom1 : (sigma(X:type,( ( big_f ) )-( ( bigX ) ))) , axiom0 : (sigma(Y:type,( ( big_g ) )-( ( bigY ) ))) ] , ( ( ( pi(X:type,( ( ( big_f ) )-( ( bigX ) ) ) -> ( ( ( big_h ) )-( ( bigX ) ) )) ) & ( pi(U:type,( ( ( big_g ) )-( ( bigU ) ) ) -> ( ( ( big_j ) )-( ( bigU ) ) )) ) ) -> ( pi(W:type,pi(Y:type,( ( ( ( big_f ) )-( ( bigW ) ) ) & ( ( ( big_g ) )-( ( bigY ) ) ) ) -> ( ( ( ( big_h ) )-( ( bigW ) ) ) & ( ( ( big_j ) )-( ( bigY ) ) ) ))) ) ) & ( ( pi(W:type,pi(Y:type,( ( ( ( big_f ) )-( ( bigW ) ) ) & ( ( ( big_g ) )-( ( bigY ) ) ) ) -> ( ( ( ( big_h ) )-( ( bigW ) ) ) & ( ( ( big_j ) )-( ( bigY ) ) ) ))) ) -> ( ( pi(X:type,( ( ( big_f ) )-( ( bigX ) ) ) -> ( ( ( big_h ) )-( ( bigX ) ) )) ) & ( pi(U:type,( ( ( big_g ) )-( ( bigU ) ) ) -> ( ( ( big_j ) )-( ( bigU ) ) )) ) ) ) , yes , '../../TPTP-v7.3.0/Problems/SYN/SYN059+1.p').

checkTheorem(syn , 73 , [ type:set ,a : (( type )) , big_i : (( ( type ) ) -> ( ( prop ) )) , big_g : (( type )) , big_h : (( type )) , big_f : (( type )) , bigX : (( type )) , axiom5 : (( ~( ( ( big_f ) )-( ( bigX ) ) ) ) \/ ( ~( ( ( big_h ) )-( ( bigX ) ) ) )) , axiom4 : (( ( ( big_g ) )-( ( bigX ) ) ) \/ ( ( ( big_f ) )-( ( bigX ) ) )) , axiom3 : (( ~( ( ( big_g ) )-( ( bigX ) ) ) ) \/ ( ~( ( ( big_h ) )-( ( bigX ) ) ) )) , axiom2 : (( ( ( big_g ) )-( ( bigX ) ) ) \/ ( ( ( big_h ) )-( ( bigX ) ) )) , axiom1 : (( ( ( big_i ) )-( ( bigX ) ) ) \/ ( ( ( big_f ) )-( ( bigX ) ) )) , axiom0 : (( ( ( big_i ) )-( ( bigX ) ) ) \/ ( ( ( big_h ) )-( ( bigX ) ) )) ] , ~( ~( ( ( big_i ) )-( ( a ) ) ) ) , no , '../../TPTP-v7.3.0/Problems/SYN/SYN060-1.p').
checkTheorem(syn , 74 , [ type:set ,big_i : (( ( type ) ) -> ( ( prop ) )) , big_h : (( type )) , big_g : (( type )) , big_f : (( type )) , axiom1 : (pi(X:type,( ( ( ( big_f ) )-( ( bigX ) ) ) \/ ( ( ( big_g ) )-( ( bigX ) ) ) ) -> ( ~( ( ( big_h ) )-( ( bigX ) ) ) ))) , axiom0 : (pi(X:type,( ( ( ( big_g ) )-( ( bigX ) ) ) -> ( ~( ( ( big_i ) )-( ( bigX ) ) ) ) ) -> ( ( ( ( big_f ) )-( ( bigX ) ) ) & ( ( ( big_h ) )-( ( bigX ) ) ) ))) ] , pi(X:type,( ( big_i ) )-( ( bigX ) )) , yes , '../../TPTP-v7.3.0/Problems/SYN/SYN060+1.p').
checkTheorem(syn , 75 , [ type:set ,big_j : (( ( type ) ) -> ( ( prop ) )) , big_i : (( ( type ) ) -> ( ( prop ) )) , a : (( type )) , big_h : (( type )) , big_g : (( type )) , big_f : (( type )) , bigX : (( type )) , axiom4 : (( ~( ( ( big_f ) )-( ( bigX ) ) ) ) \/ ( ~( ( ( big_g ) )-( ( bigX ) ) ) )) , axiom3 : (( ~( ( ( big_f ) )-( ( bigX ) ) ) ) \/ ( ~( ( ( big_h ) )-( ( bigX ) ) ) )) , axiom2 : (( ( big_i ) )-( ( a ) )) , axiom1 : (( ( big_f ) )-( ( a ) )) , axiom0 : (( ( ( big_h ) )-( ( bigX ) ) ) \/ ( ( ( big_j ) )-( ( bigX ) ) )) ] , ~( ( ~( ( ( big_i ) )-( ( bigX ) ) ) ) \/ ( ~( ( ( big_j ) )-( ( bigX ) ) ) ) ) , no , '../../TPTP-v7.3.0/Problems/SYN/SYN061-1.p').
checkTheorem(syn , 76 , [ type:set ,big_j : (( ( type ) ) -> ( ( prop ) )) , big_i : (( ( type ) ) -> ( ( prop ) )) , big_h : (( type )) , big_g : (( type )) , big_f : (( type )) , axiom2 : (~( sigma(X:type,( ( ( big_f ) )-( ( bigX ) ) ) & ( ( ( ( big_g ) )-( ( bigX ) ) ) \/ ( ( ( big_h ) )-( ( bigX ) ) ) )) )) , axiom1 : (sigma(X:type,( ( ( big_i ) )-( ( bigX ) ) ) & ( ( ( big_f ) )-( ( bigX ) ) ))) , axiom0 : (pi(X:type,( ~( ( ( big_h ) )-( ( bigX ) ) ) ) -> ( ( ( big_j ) )-( ( bigX ) ) ))) ] , sigma(X:type,( ( ( big_i ) )-( ( bigX ) ) ) & ( ( ( big_j ) )-( ( bigX ) ) )) , yes , '../../TPTP-v7.3.0/Problems/SYN/SYN061+1.p').
checkTheorem(syn , 77 , [ type:set ,a : (( type )) , big_k : (( ( type ) ) -> ( ( prop ) )) , big_j : (( ( type ) ) -> ( ( prop ) )) , big_h : (( type )) , big_i : (( type )) , big_g : (( type )) , big_f : (( ( type ) ) -> ( ( prop ) )) , bigX : (( type )) , axiom3 : (( ~( ( ( big_f ) )-( ( bigX ) ) ) ) \/ ( ( ~( ( ( big_g ) )-( ( bigX ) ) ) ) \/ ( ( ( big_i ) )-( ( bigX ) ) ) )) , axiom2 : (( ~( ( ( big_f ) )-( ( bigX ) ) ) ) \/ ( ( ~( ( ( big_h ) )-( ( bigX ) ) ) ) \/ ( ( ( big_i ) )-( ( bigX ) ) ) )) , axiom1 : (( ~( ( ( big_i ) )-( ( bigX ) ) ) ) \/ ( ( ~( ( ( big_h ) )-( ( bigX ) ) ) ) \/ ( ( ( big_j ) )-( ( bigX ) ) ) )) , axiom0 : (( ~( ( ( big_k ) )-( ( bigX ) ) ) ) \/ ( ( ( big_h ) )-( ( bigX ) ) )) ] , ( ~( ( ~( ~( ( ( big_f ) )-( ( a ) ) ) ) ) & ( ( ( big_k ) )-( ( a ) ) ) ) ) & ( ~( ( ( big_j ) )-( ( a ) ) ) ) , no , '../../TPTP-v7.3.0/Problems/SYN/SYN062-1.p').
