:- style_check(-singleton).

:-use_module(swi_alligator,[prove/2]).
:- op(500,xfx,:).
:- op(300,yfx,-).
:- op(400,xfy,=>).
:- op(400,xfy,&).
:- op(300,fy,~).
:- dynamic checktheorem/6.
writeResult(Logic,ID,Prediction,Gold,Fname) :-
format('~w&~w&~w&~w&~w~n', [Logic,ID,Prediction,Gold,Fname]).
evalyes(Logic,ID) :-
  checkTheorem(Logic,ID,Context,Theorem,Gold,Fname),
  ( prove(Context,_ : Theorem) -> writeResult(Logic,ID,yes,Gold,Fname)).
evalno(Logic,ID) :-
  checkTheorem(Logic,ID,Context,Theorem,Gold,Fname),
  ( prove(Context,_ : ( ~ (Theorem) ) ) -> writeResult(Logic,ID,no,Gold,Fname) ).
checkTheorem(syn , 390 , [ type:set ,g : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) , z : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) , f : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) , bigY : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) , bigX : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) ] , ( ~( ( ~( ( ~( ( ~( ( ~( ( ~( ~( ( ~( ( ( f ) )-( ( bigX ) )-( ( bigY ) ) ) ) \/ ( ( ( ( f ) )-( ( bigX ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) ) ) \/ ( ~( ( ( g ) )-( ( bigY ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) ) ) ) ) ) ) ) & ( ( ~( ( ( f ) )-( ( bigX ) )-( ( bigY ) ) ) ) \/ ( ( ~( ( ( f ) )-( ( bigX ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) ) ) ) \/ ( ( ( g ) )-( ( bigY ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) ) ) ) ) ) ) & ( ( ~( ( ( f ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) ) ) ) \/ ( ( ( ( g ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) ) ) \/ ( ~( ( ( f ) )-( ( bigX ) )-( ( bigY ) ) ) ) ) ) ) ) & ( ( ( ( f ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) ) ) \/ ( ( ( f ) )-( ( bigX ) )-( ( bigY ) ) ) ) ) ) & ( ( ~( ( ( g ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) ) ) ) \/ ( ( ( f ) )-( ( bigX ) )-( ( bigY ) ) ) ) ) ) & ( ( ( ( g ) )-( ( bigX ) )-( ( bigY ) ) ) \/ ( ( ( g ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) ) ) ) ) ) & ( ( ~( ( ( g ) )-( ( bigX ) )-( ( bigY ) ) ) ) \/ ( ~( ( ( g ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) ) ) ) ) , no , '../../TPTP-v7.3.0/Problems/SYN/SYN334-1.p').
checkTheorem(syn , 391 , [ type:set ,big_g : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) , big_f : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) ] , sigma(X:type,sigma(Y:type,pi(Z:type,( ( ( ( big_f ) )-( ( bigX ) )-( ( bigY ) ) ) -> ( ( ( ( ( big_f ) )-( ( bigX ) )-( ( bigZ ) ) ) -> ( ( ( big_g ) )-( ( bigY ) )-( ( bigZ ) ) ) ) & ( ( ( ( big_g ) )-( ( bigY ) )-( ( bigZ ) ) ) -> ( ( ( big_f ) )-( ( bigX ) )-( ( bigZ ) ) ) ) ) ) -> ( ( ( ( ( ( big_f ) )-( ( bigX ) )-( ( bigY ) ) ) -> ( ( ( ( big_f ) )-( ( bigZ ) )-( ( bigZ ) ) ) -> ( ( ( big_g ) )-( ( bigZ ) )-( ( bigZ ) ) ) ) ) & ( ( ( ( ( big_f ) )-( ( bigZ ) )-( ( bigZ ) ) ) -> ( ( ( big_g ) )-( ( bigZ ) )-( ( bigZ ) ) ) ) -> ( ( ( big_f ) )-( ( bigX ) )-( ( bigY ) ) ) ) ) -> ( ( ( ( ( big_g ) )-( ( bigX ) )-( ( bigY ) ) ) -> ( ( ( big_g ) )-( ( bigZ ) )-( ( bigZ ) ) ) ) & ( ( ( ( big_g ) )-( ( bigZ ) )-( ( bigZ ) ) ) -> ( ( ( big_g ) )-( ( bigX ) )-( ( bigY ) ) ) ) ) )))) , yes , '../../TPTP-v7.3.0/Problems/SYN/SYN334+1.p').
checkTheorem(syn , 392 , [ type:set ,g : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) , f : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) , z : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) , bigY : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) , bigX : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) ] , ( ~( ( ~( ( ~( ( ~( ( ~( ( ~( ( ~( ( ~( ( ~( ( ~( ( ~( ~( ( ( f ) )-( ( bigX ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) ) ) ) ) & ( ( ~( ( ( f ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) ) ) ) \/ ( ( ( ( g ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) ) ) \/ ( ~( ( ( f ) )-( ( bigX ) )-( ( bigY ) ) ) ) ) ) ) ) & ( ( ( ( f ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) ) ) \/ ( ( ( f ) )-( ( bigX ) )-( ( bigY ) ) ) ) ) ) & ( ( ~( ( ( g ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) ) ) ) \/ ( ( ( f ) )-( ( bigX ) )-( ( bigY ) ) ) ) ) ) & ( ( ~( ( ( g ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) ) ) ) \/ ( ( ( ( f ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) ) ) \/ ( ~( ( ( g ) )-( ( bigX ) )-( ( bigY ) ) ) ) ) ) ) ) & ( ( ( ( g ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) ) ) \/ ( ( ( g ) )-( ( bigX ) )-( ( bigY ) ) ) ) ) ) & ( ( ~( ( ( f ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) ) ) ) \/ ( ( ( g ) )-( ( bigX ) )-( ( bigY ) ) ) ) ) ) & ( ( ~( ( ( g ) )-( ( bigX ) )-( ( bigY ) ) ) ) \/ ( ( ( ( f ) )-( ( bigY ) )-( ( bigX ) ) ) \/ ( ~( ( ( g ) )-( ( bigY ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) ) ) ) ) ) ) ) & ( ( ( ( g ) )-( ( bigX ) )-( ( bigY ) ) ) \/ ( ( ( g ) )-( ( bigY ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) ) ) ) ) ) & ( ( ~( ( ( f ) )-( ( bigY ) )-( ( bigX ) ) ) ) \/ ( ( ( g ) )-( ( bigY ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) ) ) ) ) ) & ( ( ( ( f ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) )-( ( bigY ) ) ) \/ ( ( ( f ) )-( ( bigY ) )-( ( bigX ) ) ) ) ) ) & ( ( ~( ( ( f ) )-( ( ( z ) )-( ( bigX ) )-( ( bigY ) ) )-( ( bigY ) ) ) ) \/ ( ~( ( ( f ) )-( ( bigY ) )-( ( bigX ) ) ) ) ) , unknown , '../../TPTP-v7.3.0/Problems/SYN/SYN335-1.p').
checkTheorem(syn , 393 , [ type:set ,big_g : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) , big_f : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) ] , sigma(X:type,sigma(Y:type,pi(Z:type,( ( ( big_f ) )-( ( bigX ) )-( ( bigZ ) ) ) -> ( ( ( ( ( ( ( big_f ) )-( ( bigZ ) )-( ( bigZ ) ) ) -> ( ( ( big_g ) )-( ( bigZ ) )-( ( bigZ ) ) ) ) -> ( ( ( big_f ) )-( ( bigX ) )-( ( bigY ) ) ) ) & ( ( ( ( big_f ) )-( ( bigX ) )-( ( bigY ) ) ) -> ( ( ( ( big_f ) )-( ( bigZ ) )-( ( bigZ ) ) ) -> ( ( ( big_g ) )-( ( bigZ ) )-( ( bigZ ) ) ) ) ) ) -> ( ( ( ( ( ( ( big_g ) )-( ( bigZ ) )-( ( bigZ ) ) ) -> ( ( ( big_f ) )-( ( bigZ ) )-( ( bigZ ) ) ) ) -> ( ( ( big_g ) )-( ( bigX ) )-( ( bigY ) ) ) ) & ( ( ( ( big_g ) )-( ( bigX ) )-( ( bigY ) ) ) -> ( ( ( ( big_g ) )-( ( bigZ ) )-( ( bigZ ) ) ) -> ( ( ( big_f ) )-( ( bigZ ) )-( ( bigZ ) ) ) ) ) ) -> ( ( ( ( ( ( ( big_g ) )-( ( bigX ) )-( ( bigY ) ) ) -> ( ( ( big_f ) )-( ( bigY ) )-( ( bigX ) ) ) ) -> ( ( ( big_g ) )-( ( bigY ) )-( ( bigZ ) ) ) ) & ( ( ( ( big_g ) )-( ( bigY ) )-( ( bigZ ) ) ) -> ( ( ( ( big_g ) )-( ( bigX ) )-( ( bigY ) ) ) -> ( ( ( big_f ) )-( ( bigY ) )-( ( bigX ) ) ) ) ) ) -> ( ( ( ( ( big_f ) )-( ( bigZ ) )-( ( bigY ) ) ) -> ( ( ( big_f ) )-( ( bigY ) )-( ( bigX ) ) ) ) & ( ( ( ( big_f ) )-( ( bigY ) )-( ( bigX ) ) ) -> ( ( ( big_f ) )-( ( bigZ ) )-( ( bigY ) ) ) ) ) ) ) )))) , no , '../../TPTP-v7.3.0/Problems/SYN/SYN335+1.p').
checkTheorem(syn , 394 , [ type:set ,f : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) , z : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) , bigY2 : (( type )) , bigY1 : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) , a : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) ] , ( ~( ( ~( ( ~( ( ~( ~( ( ( f ) )-( ( a ) )-( ( ( z ) )-( ( bigY1 ) )-( ( bigY2 ) ) ) ) ) ) & ( ( ( f ) )-( ( bigY1 ) )-( ( ( z ) )-( ( bigY1 ) )-( ( bigY2 ) ) ) ) ) ) & ( ( ( f ) )-( ( bigY2 ) )-( ( ( z ) )-( ( bigY1 ) )-( ( bigY2 ) ) ) ) ) ) & ( ( ( f ) )-( ( bigY1 ) )-( ( a ) ) ) ) ) & ( ~( ( ( f ) )-( ( ( z ) )-( ( bigY1 ) )-( ( bigY2 ) ) )-( ( bigY2 ) ) ) ) , no , '../../TPTP-v7.3.0/Problems/SYN/SYN336-1.p').
checkTheorem(syn , 395 , [ type:set ,big_f : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) ] , pi(X:type,sigma(Y1:type,sigma(Y2:type,pi(Z:type,( ( ( big_f ) )-( ( bigX ) )-( ( bigZ ) ) ) -> ( ( ( ( big_f ) )-( ( bigY1 ) )-( ( bigZ ) ) ) -> ( ( ( ( big_f ) )-( ( bigY2 ) )-( ( bigZ ) ) ) -> ( ( ( ( big_f ) )-( ( bigY1 ) )-( ( bigX ) ) ) -> ( ( ( big_f ) )-( ( bigZ ) )-( ( bigY2 ) ) ) ) ) ))))) , yes , '../../TPTP-v7.3.0/Problems/SYN/SYN336+1.p').
