:- style_check(-singleton).

:-use_module(swi_alligator,[prove/2]).
:- op(500,xfx,:).
:- op(300,yfx,-).
:- op(400,xfy,=>).
:- op(400,xfy,&).
:- op(300,fy,~).
:- dynamic checktheorem/6.
writeResult(Logic,ID,Prediction,Gold,Fname) :-
format('~w&~w&~w&~w&~w~n', [Logic,ID,Prediction,Gold,Fname]).
evalyes(Logic,ID) :-
  checkTheorem(Logic,ID,Context,Theorem,Gold,Fname),
  ( prove(Context,_ : Theorem) -> writeResult(Logic,ID,yes,Gold,Fname)).
evalno(Logic,ID) :-
  checkTheorem(Logic,ID,Context,Theorem,Gold,Fname),
  ( prove(Context,_ : ( ~ (Theorem) ) ) -> writeResult(Logic,ID,no,Gold,Fname) ).
checkTheorem(syn , 408 , [ type:set ,big_f : (( ( type ) ) -> ( ( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) ) )) ] , pi(X1:type,sigma(X2:type,pi(X3:type,sigma(X4:type,( ( ( big_f ) )-( ( bigX1 ) )-( ( bigX2 ) )-( ( bigX3 ) ) ) -> ( ( ( big_f ) )-( ( bigX4 ) )-( ( bigX4 ) )-( ( bigX1 ) ) ))))) , no , '../../TPTP-v7.3.0/Problems/SYN/SYN342+1.p').
checkTheorem(syn , 409 , [ type:set ,z : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) , bigY2 : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) , f : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) , bigY1 : (( type )) , a : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) ] , ( ~( ( ~( ~( ( ( ( f ) )-( ( a ) )-( ( bigY1 ) ) ) \/ ( ( ( f ) )-( ( a ) )-( ( a ) ) ) ) ) ) & ( ( ~( ( ( f ) )-( ( ( z ) )-( ( bigY1 ) )-( ( bigY2 ) ) )-( ( a ) ) ) ) \/ ( ( ( f ) )-( ( a ) )-( ( a ) ) ) ) ) ) & ( ( ~( ( ( f ) )-( ( a ) )-( ( a ) ) ) ) \/ ( ~( ( ( f ) )-( ( bigY1 ) )-( ( bigY2 ) ) ) ) ) , no , '../../TPTP-v7.3.0/Problems/SYN/SYN343-1.p').
checkTheorem(syn , 410 , [ type:set ,big_f : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) ] , sigma(X:type,sigma(Y1:type,sigma(Y2:type,pi(Z:type,( ( ( ( ( big_f ) )-( ( bigX ) )-( ( bigY1 ) ) ) -> ( ( ( big_f ) )-( ( bigZ ) )-( ( bigX ) ) ) ) -> ( ( ( big_f ) )-( ( bigX ) )-( ( bigX ) ) ) ) -> ( ( ( ( big_f ) )-( ( bigX ) )-( ( bigX ) ) ) & ( ( ( big_f ) )-( ( bigY1 ) )-( ( bigY2 ) ) ) ))))) , yes , '../../TPTP-v7.3.0/Problems/SYN/SYN343+1.p').
checkTheorem(syn , 411 , [ type:set ,f : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) , z : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) , bigY2 : (( type )) , bigY1 : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) , a : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) ] , ( ~( ( ~( ( ~( ( ~( ~( ( ( ( f ) )-( ( a ) )-( ( ( z ) )-( ( bigY1 ) )-( ( bigY2 ) ) ) ) \/ ( ( ( f ) )-( ( a ) )-( ( a ) ) ) ) ) ) & ( ( ( ( f ) )-( ( bigY1 ) )-( ( ( z ) )-( ( bigY1 ) )-( ( bigY2 ) ) ) ) \/ ( ( ( f ) )-( ( a ) )-( ( a ) ) ) ) ) ) & ( ( ~( ( ( f ) )-( ( bigY2 ) )-( ( a ) ) ) ) \/ ( ( ( f ) )-( ( a ) )-( ( a ) ) ) ) ) ) & ( ( ~( ( ( f ) )-( ( a ) )-( ( a ) ) ) ) \/ ( ( ( f ) )-( ( bigY1 ) )-( ( bigY2 ) ) ) ) ) ) & ( ( ~( ( ( f ) )-( ( a ) )-( ( a ) ) ) ) \/ ( ~( ( ( f ) )-( ( ( z ) )-( ( bigY1 ) )-( ( bigY2 ) ) )-( ( ( z ) )-( ( bigY1 ) )-( ( bigY2 ) ) ) ) ) ) , unknown , '../../TPTP-v7.3.0/Problems/SYN/SYN344-1.p').
checkTheorem(syn , 412 , [ type:set ,big_f : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) ] , pi(X:type,sigma(Y1:type,sigma(Y2:type,pi(Z:type,( ( ( ( ( big_f ) )-( ( bigX ) )-( ( bigZ ) ) ) -> ( ( ( ( big_f ) )-( ( bigY1 ) )-( ( bigZ ) ) ) -> ( ( ( big_f ) )-( ( bigY2 ) )-( ( bigX ) ) ) ) ) -> ( ( ( big_f ) )-( ( bigX ) )-( ( bigX ) ) ) ) -> ( ( ( ( big_f ) )-( ( bigX ) )-( ( bigX ) ) ) & ( ( ( ( big_f ) )-( ( bigY1 ) )-( ( bigY2 ) ) ) -> ( ( ( big_f ) )-( ( bigZ ) )-( ( bigZ ) ) ) ) ))))) , no , '../../TPTP-v7.3.0/Problems/SYN/SYN344+1.p').
checkTheorem(syn , 413 , [ type:set ,z : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) , bigY2 : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) , f : (( ( type ) ) -> ( ( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) ) )) , bigY1 : (( type )) , b : (( type )) , a : (( ( type ) ) -> ( ( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) ) )) ] , ( ~( ( ~( ( ~( ( ~( ( ~( ( ~( ( ~( ~( ( ( ( f ) )-( ( a ) )-( ( b ) )-( ( bigY1 ) ) ) \/ ( ( ~( ( ( f ) )-( ( a ) )-( ( a ) )-( ( b ) ) ) ) \/ ( ( ( f ) )-( ( a ) )-( ( b ) )-( ( b ) ) ) ) ) ) ) & ( ( ~( ( ( f ) )-( ( bigY2 ) )-( ( bigY1 ) )-( ( ( z ) )-( ( bigY1 ) )-( ( bigY2 ) ) ) ) ) \/ ( ( ~( ( ( f ) )-( ( a ) )-( ( a ) )-( ( b ) ) ) ) \/ ( ( ( f ) )-( ( a ) )-( ( b ) )-( ( b ) ) ) ) ) ) ) & ( ( ( ( f ) )-( ( b ) )-( ( bigY1 ) )-( ( bigY2 ) ) ) \/ ( ( ( ( f ) )-( ( a ) )-( ( a ) )-( ( b ) ) ) \/ ( ~( ( ( f ) )-( ( a ) )-( ( b ) )-( ( b ) ) ) ) ) ) ) ) & ( ( ~( ( ( f ) )-( ( bigY1 ) )-( ( ( z ) )-( ( bigY1 ) )-( ( bigY2 ) ) )-( ( ( z ) )-( ( bigY1 ) )-( ( bigY2 ) ) ) ) ) \/ ( ( ( ( f ) )-( ( a ) )-( ( a ) )-( ( b ) ) ) \/ ( ~( ( ( f ) )-( ( a ) )-( ( b ) )-( ( b ) ) ) ) ) ) ) ) & ( ( ( ( f ) )-( ( bigY1 ) )-( ( bigY2 ) )-( ( ( z ) )-( ( bigY1 ) )-( ( bigY2 ) ) ) ) \/ ( ( ( ( f ) )-( ( a ) )-( ( a ) )-( ( b ) ) ) \/ ( ( ( f ) )-( ( a ) )-( ( b ) )-( ( b ) ) ) ) ) ) ) & ( ( ( ( f ) )-( ( bigY1 ) )-( ( bigY2 ) )-( ( ( z ) )-( ( bigY1 ) )-( ( bigY2 ) ) ) ) \/ ( ( ~( ( ( f ) )-( ( a ) )-( ( a ) )-( ( b ) ) ) ) \/ ( ~( ( ( f ) )-( ( a ) )-( ( b ) )-( ( b ) ) ) ) ) ) ) ) & ( ( ~( ( ( f ) )-( ( b ) )-( ( b ) )-( ( bigY1 ) ) ) ) \/ ( ( ( ( f ) )-( ( a ) )-( ( a ) )-( ( b ) ) ) \/ ( ( ( f ) )-( ( a ) )-( ( b ) )-( ( b ) ) ) ) ) ) ) & ( ( ~( ( ( f ) )-( ( b ) )-( ( b ) )-( ( bigY1 ) ) ) ) \/ ( ( ~( ( ( f ) )-( ( a ) )-( ( a ) )-( ( b ) ) ) ) \/ ( ~( ( ( f ) )-( ( a ) )-( ( b ) )-( ( b ) ) ) ) ) ) , no , '../../TPTP-v7.3.0/Problems/SYN/SYN345-1.p').
