:- style_check(-singleton).

:-use_module(swi_alligator,[prove/2]).
:- op(500,xfx,:).
:- op(300,yfx,-).
:- op(400,xfy,=>).
:- op(400,xfy,&).
:- op(300,fy,~).
:- dynamic checktheorem/6.
writeResult(Logic,ID,Prediction,Gold,Fname) :-
format('~w&~w&~w&~w&~w~n', [Logic,ID,Prediction,Gold,Fname]).
evalyes(Logic,ID) :-
  checkTheorem(Logic,ID,Context,Theorem,Gold,Fname),
  ( prove(Context,_ : Theorem) -> writeResult(Logic,ID,yes,Gold,Fname)).
evalno(Logic,ID) :-
  checkTheorem(Logic,ID,Context,Theorem,Gold,Fname),
  ( prove(Context,_ : ( ~ (Theorem) ) ) -> writeResult(Logic,ID,no,Gold,Fname) ).
checkTheorem(syn , 60 , [ type:set ,big_f : (( ( type ) ) -> ( ( prop ) )) , p : (( ( type ) ) -> ( ( prop ) )) ] , ( ( pi(X:type,( ( p ) ) \/ ( ( ( big_f ) )-( ( bigX ) ) )) ) -> ( ( ( p ) ) \/ ( pi(X1:type,( ( big_f ) )-( ( bigX1 ) )) ) ) ) & ( ( ( ( p ) ) \/ ( pi(X1:type,( ( big_f ) )-( ( bigX1 ) )) ) ) -> ( pi(X:type,( ( p ) ) \/ ( ( ( big_f ) )-( ( bigX ) ) )) ) ) , yes , '../../TPTP-v7.3.0/Problems/SYN/SYN053+1.p').
checkTheorem(syn , 61 , [ type:set ,b : (( type )) , a : (( type )) , big_r : (( ( type ) ) -> ( ( prop ) )) , big_p : (( ( type ) ) -> ( ( prop ) )) , big_q : (( type )) , big_s : (( ( type ) ) -> ( ( prop ) )) , bigX : (( type )) , axiom3 : (( ~( ( ( big_s ) )-( ( bigX ) ) ) ) \/ ( ~( ( ( big_q ) )-( ( bigX ) ) ) )) , axiom2 : (( ~( ( ( big_p ) )-( ( bigX ) ) ) ) \/ ( ( ( ( big_q ) )-( ( bigX ) ) ) \/ ( ( ( big_r ) )-( ( bigX ) ) ) )) , axiom1 : (( ( ( big_p ) )-( ( a ) ) ) \/ ( ( ( big_q ) )-( ( b ) ) )) , axiom0 : (( ~( ( ( big_q ) )-( ( bigX ) ) ) ) \/ ( ( ( big_s ) )-( ( bigX ) ) )) ] , ( ~( ~( ( ~( ( ( big_r ) )-( ( bigX ) ) ) ) \/ ( ( ( big_s ) )-( ( bigX ) ) ) ) ) ) & ( ( ~( ( ( big_p ) )-( ( bigX ) ) ) ) \/ ( ~( ( ( big_r ) )-( ( bigX ) ) ) ) ) , no , '../../TPTP-v7.3.0/Problems/SYN/SYN054-1.p').
checkTheorem(syn , 62 , [ type:set ,big_r : (( ( type ) ) -> ( ( prop ) )) , big_p : (( ( type ) ) -> ( ( prop ) )) , big_q : (( type )) , big_s : (( type )) , axiom3 : (~( sigma(X:type,( ( ( big_s ) )-( ( bigX ) ) ) & ( ( ( big_q ) )-( ( bigX ) ) )) )) , axiom2 : (pi(X:type,( ( ( big_p ) )-( ( bigX ) ) ) -> ( ( ( ( big_q ) )-( ( bigX ) ) ) \/ ( ( ( big_r ) )-( ( bigX ) ) ) ))) , axiom1 : (( ~( sigma(X:type,( ( big_p ) )-( ( bigX ) )) ) ) -> ( sigma(Y:type,( ( big_q ) )-( ( bigY ) )) )) , axiom0 : (pi(X:type,( ( ( ( big_q ) )-( ( bigX ) ) ) \/ ( ( ( big_r ) )-( ( bigX ) ) ) ) -> ( ( ( big_s ) )-( ( bigX ) ) ))) ] , sigma(X:type,( ( ( big_p ) )-( ( bigX ) ) ) & ( ( ( big_r ) )-( ( bigX ) ) )) , yes , '../../TPTP-v7.3.0/Problems/SYN/SYN054+1.p').
checkTheorem(syn , 63 , [ type:set ,b : (( type )) , big_q : (( ( type ) ) -> ( ( prop ) )) , big_r : (( ( type ) ) -> ( ( prop ) )) , big_g : (( type )) , big_f : (( type )) , bigX : (( type )) , big_p : (( ( type ) ) -> ( ( prop ) )) , a : (( type )) , axiom4 : (( ( big_p ) )-( ( a ) )) , axiom3 : (( ~( ( ( big_f ) )-( ( bigX ) ) ) ) \/ ( ( ~( ( ( big_g ) )-( ( bigX ) ) ) ) \/ ( ~( ( ( big_r ) )-( ( bigX ) ) ) ) )) , axiom2 : (( ~( ( ( big_p ) )-( ( bigX ) ) ) ) \/ ( ( ( big_f ) )-( ( bigX ) ) )) , axiom1 : (( ~( ( ( big_p ) )-( ( bigX ) ) ) ) \/ ( ( ( big_g ) )-( ( bigX ) ) )) , axiom0 : (( ~( ( ( big_p ) )-( ( bigX ) ) ) ) \/ ( ( ( ( big_q ) )-( ( bigX ) ) ) \/ ( ( ( big_p ) )-( ( b ) ) ) )) ] , ( ~( ~( ( ~( ( ( big_p ) )-( ( bigX ) ) ) ) \/ ( ( ( ( big_q ) )-( ( bigX ) ) ) \/ ( ( ( big_r ) )-( ( b ) ) ) ) ) ) ) & ( ( ~( ( ( big_q ) )-( ( bigX ) ) ) ) \/ ( ~( ( ( big_p ) )-( ( bigX ) ) ) ) ) , no , '../../TPTP-v7.3.0/Problems/SYN/SYN055-1.p').
checkTheorem(syn , 64 , [ type:set ,big_q : (( ( type ) ) -> ( ( prop ) )) , big_r : (( type )) , big_g : (( type )) , big_f : (( type )) , big_p : (( ( type ) ) -> ( ( prop ) )) , axiom3 : (sigma(X:type,( ( big_p ) )-( ( bigX ) ))) , axiom2 : (pi(X:type,( ( ( big_f ) )-( ( bigX ) ) ) -> ( ( ~( ( ( big_g ) )-( ( bigX ) ) ) ) & ( ( ( big_r ) )-( ( bigX ) ) ) ))) , axiom1 : (pi(X:type,( ( ( big_p ) )-( ( bigX ) ) ) -> ( ( ( ( big_g ) )-( ( bigX ) ) ) & ( ( ( big_f ) )-( ( bigX ) ) ) ))) , axiom0 : (( pi(X:type,( ( ( big_p ) )-( ( bigX ) ) ) -> ( ( ( big_q ) )-( ( bigX ) ) )) ) \/ ( sigma(Z:type,( ( ( big_p ) )-( ( bigZ ) ) ) & ( ( ( big_r ) )-( ( bigZ ) ) )) )) ] , sigma(X:type,( ( ( big_q ) )-( ( bigX ) ) ) & ( ( ( big_p ) )-( ( bigX ) ) )) , yes , '../../TPTP-v7.3.0/Problems/SYN/SYN055+1.p').

checkTheorem(syn , 65 , [ type:set ,d : (( type )) , c : (( type )) , big_s : (( ( type ) ) -> ( ( prop ) )) , big_r : (( ( type ) ) -> ( ( prop ) )) , bigY : (( type )) , b : (( type )) , big_q : (( ( type ) ) -> ( ( prop ) )) , a : (( type )) , big_p : (( ( type ) ) -> ( ( prop ) )) , bigX : (( type )) , axiom4 : (( ~( ( ( big_p ) )-( ( bigX ) ) ) ) \/ ( ( ( big_q ) )-( ( a ) ) )) , axiom3 : (( ~( ( ( big_q ) )-( ( bigX ) ) ) ) \/ ( ( ( big_p ) )-( ( b ) ) )) , axiom2 : (( ~( ( ( big_p ) )-( ( bigX ) ) ) ) \/ ( ( ~( ( ( big_q ) )-( ( bigY ) ) ) ) \/ ( ( ~( ( ( big_r ) )-( ( bigX ) ) ) ) \/ ( ( ( big_s ) )-( ( bigY ) ) ) ) )) , axiom1 : (( ~( ( ( big_p ) )-( ( bigX ) ) ) ) \/ ( ( ~( ( ( big_q ) )-( ( bigY ) ) ) ) \/ ( ( ~( ( ( big_s ) )-( ( bigY ) ) ) ) \/ ( ( ( big_r ) )-( ( bigX ) ) ) ) )) , axiom0 : (( ~( ( ( big_p ) )-( ( bigX ) ) ) ) \/ ( ( ~( ( ( big_q ) )-( ( bigX ) ) ) ) \/ ( ( ( ( big_r ) )-( ( bigX ) ) ) \/ ( ( ( big_s ) )-( ( bigX ) ) ) ) )) ] , ( ~( ( ~( ( ~( ( ~( ( ~( ( ~( ( ~( ~( ( ~( ( ( big_p ) )-( ( bigX ) ) ) ) \/ ( ( ( ( big_p ) )-( ( c ) ) ) \/ ( ( ( big_r ) )-( ( bigX ) ) ) ) ) ) ) & ( ( ~( ( ( big_p ) )-( ( bigX ) ) ) ) \/ ( ( ~( ( ( big_r ) )-( ( c ) ) ) ) \/ ( ( ( big_r ) )-( ( bigX ) ) ) ) ) ) ) & ( ( ~( ( ( big_q ) )-( ( bigX ) ) ) ) \/ ( ( ( ( big_q ) )-( ( d ) ) ) \/ ( ( ( big_s ) )-( ( bigX ) ) ) ) ) ) ) & ( ( ~( ( ( big_q ) )-( ( bigX ) ) ) ) \/ ( ( ~( ( ( big_s ) )-( ( d ) ) ) ) \/ ( ( ( big_s ) )-( ( bigX ) ) ) ) ) ) ) & ( ( ( ( big_p ) )-( ( c ) ) ) \/ ( ( ( big_q ) )-( ( d ) ) ) ) ) ) & ( ( ~( ( ( big_r ) )-( ( c ) ) ) ) \/ ( ( ( big_q ) )-( ( d ) ) ) ) ) ) & ( ( ~( ( ( big_s ) )-( ( d ) ) ) ) \/ ( ( ( big_p ) )-( ( c ) ) ) ) ) ) & ( ( ~( ( ( big_r ) )-( ( c ) ) ) ) \/ ( ~( ( ( big_s ) )-( ( d ) ) ) ) ) , unknown , '../../TPTP-v7.3.0/Problems/SYN/SYN056-1.p').
