:- style_check(-singleton).

:-use_module(swi_alligator,[prove/2]).
:- op(500,xfx,:).
:- op(300,yfx,-).
:- op(400,xfy,=>).
:- op(400,xfy,&).
:- op(300,fy,~).
:- dynamic checktheorem/6.
writeResult(Logic,ID,Prediction,Gold,Fname) :-
format('~w&~w&~w&~w&~w~n', [Logic,ID,Prediction,Gold,Fname]).
evalyes(Logic,ID) :-
  checkTheorem(Logic,ID,Context,Theorem,Gold,Fname),
  ( prove(Context,_ : Theorem) -> writeResult(Logic,ID,yes,Gold,Fname)).
evalno(Logic,ID) :-
  checkTheorem(Logic,ID,Context,Theorem,Gold,Fname),
  ( prove(Context,_ : ( ~ (Theorem) ) ) -> writeResult(Logic,ID,no,Gold,Fname) ).
checkTheorem(syn , 78 , [ type:set ,big_k : (( ( type ) ) -> ( ( prop ) )) , big_j : (( ( type ) ) -> ( ( prop ) )) , big_i : (( type )) , big_h : (( type )) , big_g : (( type )) , big_f : (( ( type ) ) -> ( ( prop ) )) , axiom2 : (pi(X:type,( ( ( ( big_f ) )-( ( bigX ) ) ) & ( ( ( ( big_g ) )-( ( bigX ) ) ) \/ ( ( ( big_h ) )-( ( bigX ) ) ) ) ) -> ( ( ( big_i ) )-( ( bigX ) ) ))) , axiom1 : (pi(X:type,( ( ( ( big_i ) )-( ( bigX ) ) ) & ( ( ( big_h ) )-( ( bigX ) ) ) ) -> ( ( ( big_j ) )-( ( bigX ) ) ))) , axiom0 : (pi(X:type,( ( ( big_k ) )-( ( bigX ) ) ) -> ( ( ( big_h ) )-( ( bigX ) ) ))) ] , pi(X:type,( ( ( ( big_f ) )-( ( bigX ) ) ) & ( ( ( big_k ) )-( ( bigX ) ) ) ) -> ( ( ( big_j ) )-( ( bigX ) ) )) , yes , '../../TPTP-v7.3.0/Problems/SYN/SYN062+1.p').
checkTheorem(syn , 79 , [ type:set ,d : (( type )) , e : (( type )) , b : (( type )) , bigY : (( type )) , c : (( type )) , bigX : (( type )) , big_p : (( ( type ) ) -> ( ( prop ) )) , a : (( ( type ) ) -> ( ( prop ) )) ] , ( ~( ( ~( ( ~( ( ~( ( ~( ( ~( ~( ( ( big_p ) )-( ( a ) ) ) ) ) & ( ( ~( ( ( big_p ) )-( ( a ) ) ) ) \/ ( ( ( ( big_p ) )-( ( bigX ) ) ) \/ ( ( ( ( big_p ) )-( ( c ) ) ) \/ ( ( ( big_p ) )-( ( bigY ) ) ) ) ) ) ) ) & ( ( ~( ( ( big_p ) )-( ( a ) ) ) ) \/ ( ( ~( ( ( big_p ) )-( ( b ) ) ) ) \/ ( ( ( big_p ) )-( ( c ) ) ) ) ) ) ) & ( ~( ( ( big_p ) )-( ( c ) ) ) ) ) ) & ( ( ~( ( ( big_p ) )-( ( e ) ) ) ) \/ ( ( ( ( big_p ) )-( ( b ) ) ) \/ ( ~( ( ( big_p ) )-( ( d ) ) ) ) ) ) ) ) & ( ( ~( ( ( big_p ) )-( ( a ) ) ) ) \/ ( ( ( ( big_p ) )-( ( bigX ) ) ) \/ ( ( ( ( big_p ) )-( ( c ) ) ) \/ ( ( ~( ( ( big_p ) )-( ( d ) ) ) ) \/ ( ( ( big_p ) )-( ( b ) ) ) ) ) ) ) ) ) & ( ( ~( ( ( big_p ) )-( ( e ) ) ) ) \/ ( ( ( ( big_p ) )-( ( b ) ) ) \/ ( ( ~( ( ( big_p ) )-( ( a ) ) ) ) \/ ( ( ( ( big_p ) )-( ( bigX ) ) ) \/ ( ( ( big_p ) )-( ( c ) ) ) ) ) ) ) , no , '../../TPTP-v7.3.0/Problems/SYN/SYN063-1.p').
checkTheorem(syn , 80 , [ type:set ,c : (( type )) , b : (( type )) , big_p : (( ( type ) ) -> ( ( prop ) )) , a : (( ( type ) ) -> ( ( prop ) )) ] , ( ( pi(X:type,( ( ( ( big_p ) )-( ( a ) ) ) & ( ( ( ( big_p ) )-( ( bigX ) ) ) -> ( ( ( big_p ) )-( ( b ) ) ) ) ) -> ( ( ( big_p ) )-( ( c ) ) )) ) -> ( pi(X1:type,( ( ~( ( ( big_p ) )-( ( a ) ) ) ) \/ ( ( ( ( big_p ) )-( ( bigX1 ) ) ) \/ ( ( ( big_p ) )-( ( c ) ) ) ) ) & ( ( ~( ( ( big_p ) )-( ( a ) ) ) ) \/ ( ( ~( ( ( big_p ) )-( ( b ) ) ) ) \/ ( ( ( big_p ) )-( ( c ) ) ) ) )) ) ) & ( ( pi(X1:type,( ( ~( ( ( big_p ) )-( ( a ) ) ) ) \/ ( ( ( ( big_p ) )-( ( bigX1 ) ) ) \/ ( ( ( big_p ) )-( ( c ) ) ) ) ) & ( ( ~( ( ( big_p ) )-( ( a ) ) ) ) \/ ( ( ~( ( ( big_p ) )-( ( b ) ) ) ) \/ ( ( ( big_p ) )-( ( c ) ) ) ) )) ) -> ( pi(X:type,( ( ( ( big_p ) )-( ( a ) ) ) & ( ( ( ( big_p ) )-( ( bigX ) ) ) -> ( ( ( big_p ) )-( ( b ) ) ) ) ) -> ( ( ( big_p ) )-( ( c ) ) )) ) ) , yes , '../../TPTP-v7.3.0/Problems/SYN/SYN063+1.p').
checkTheorem(syn , 81 , [ type:set ,a : (( type )) , big_p : (( ( type ) ) -> ( ( prop ) )) , c : (( ( type ) ) -> ( ( prop ) )) ] , ( ~( ( ~( ~( ( ( ( big_p ) )-( ( c ) ) ) \/ ( ~( ( ( big_p ) )-( ( a ) ) ) ) ) ) ) & ( ( ( big_p ) )-( ( a ) ) ) ) ) & ( ~( ( ( big_p ) )-( ( c ) ) ) ) , no , '../../TPTP-v7.3.0/Problems/SYN/SYN063-2.p').
checkTheorem(syn , 82 , [ type:set ,g : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) , f : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) , big_p : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) , bigY : (( type )) , bigX : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) ] , ( ~( ~( ( ( big_p ) )-( ( bigX ) )-( ( bigY ) ) ) ) ) & ( ~( ( ( big_p ) )-( ( ( f ) )-( ( bigX ) )-( ( bigY ) ) )-( ( ( g ) )-( ( bigX ) )-( ( bigY ) ) ) ) ) , no , '../../TPTP-v7.3.0/Problems/SYN/SYN064-1.p').
checkTheorem(syn , 83 , [ type:set ,big_p : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) ] , sigma(X:type,sigma(Y:type,( ( ( big_p ) )-( ( bigX ) )-( ( bigY ) ) ) -> ( pi(Z:type,pi(W:type,( ( big_p ) )-( ( bigZ ) )-( ( bigW ) ))) ))) , yes , '../../TPTP-v7.3.0/Problems/SYN/SYN064+1.p').
