:- style_check(-singleton).

:-use_module(swi_alligator,[prove/2]).
:- op(500,xfx,:).
:- op(300,yfx,-).
:- op(400,xfy,=>).
:- op(400,xfy,&).
:- op(300,fy,~).
:- dynamic checktheorem/6.
writeResult(Logic,ID,Prediction,Gold,Fname) :-
format('~w&~w&~w&~w&~w~n', [Logic,ID,Prediction,Gold,Fname]).
evalyes(Logic,ID) :-
  checkTheorem(Logic,ID,Context,Theorem,Gold,Fname),
  ( prove(Context,_ : Theorem) -> writeResult(Logic,ID,yes,Gold,Fname)).
evalno(Logic,ID) :-
  checkTheorem(Logic,ID,Context,Theorem,Gold,Fname),
  ( prove(Context,_ : ( ~ (Theorem) ) ) -> writeResult(Logic,ID,no,Gold,Fname) ).
checkTheorem(syn , 108 , [ type:set ,big_f : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) , c : (( type )) , f : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) , b : (( type )) , a : (( type )) , axiom2 : (( ( big_f ) )-( ( ( f ) )-( ( a ) )-( ( b ) ) )-( ( ( f ) )-( ( b ) )-( ( c ) ) )) , axiom1 : (( ( big_f ) )-( ( ( f ) )-( ( b ) )-( ( c ) ) )-( ( ( f ) )-( ( a ) )-( ( c ) ) )) , axiom0 : (pi(X:type,pi(Y:type,pi(Z:type,( ( ( ( big_f ) )-( ( bigX ) )-( ( bigY ) ) ) & ( ( ( big_f ) )-( ( bigY ) )-( ( bigZ ) ) ) ) -> ( ( ( big_f ) )-( ( bigX ) )-( ( bigZ ) ) ))))) ] , ( ( big_f ) )-( ( ( f ) )-( ( a ) )-( ( b ) ) )-( ( ( f ) )-( ( a ) )-( ( c ) ) ) , yes , '../../TPTP-v7.3.0/Problems/SYN/SYN079+1.p').
checkTheorem(syn , 109 , [ type:set ,b : (( type )) , a : (( type )) , g : (( ( type ) ) -> ( ( prop ) )) , bigY : (( type )) , f : (( ( type ) ) -> ( ( prop ) )) , bigX : (( type )) , axiom0 : (( ( ( ( f ) )-( ( bigX ) ) ) -> ( ( ( g ) )-( ( bigY ) ) ) ) & ( ( ( ( g ) )-( ( bigY ) ) ) -> ( ( ( f ) )-( ( bigX ) ) ) )) ] , ~( ~( ( ( ( ( f ) )-( ( ( f ) )-( ( a ) ) ) ) -> ( ( ( f ) )-( ( ( g ) )-( ( b ) ) ) ) ) & ( ( ( ( f ) )-( ( ( g ) )-( ( b ) ) ) ) -> ( ( ( f ) )-( ( ( f ) )-( ( a ) ) ) ) ) ) ) , no , '../../TPTP-v7.3.0/Problems/SYN/SYN080-1.p').
checkTheorem(syn , 110 , [ type:set ,g : (( ( type ) ) -> ( ( prop ) )) , bigY : (( type )) , f : (( ( type ) ) -> ( ( prop ) )) , axiom0 : (( ( pi(X:type,pi(Y:type,( ( f ) )-( ( bigX ) ))) ) -> ( ( ( g ) )-( ( bigY ) ) ) ) & ( ( ( ( g ) )-( ( bigY ) ) ) -> ( pi(X:type,pi(Y:type,( ( f ) )-( ( bigX ) ))) ) )) ] , ( ( pi(X:type,pi(Y:type,( ( f ) )-( ( ( f ) )-( ( bigX ) ) ))) ) -> ( ( ( f ) )-( ( ( g ) )-( ( bigY ) ) ) ) ) & ( ( ( ( f ) )-( ( ( g ) )-( ( bigY ) ) ) ) -> ( pi(X:type,pi(Y:type,( ( f ) )-( ( ( f ) )-( ( bigX ) ) ))) ) ) , yes , '../../TPTP-v7.3.0/Problems/SYN/SYN080+1.p').
checkTheorem(syn , 111 , [ type:set ,f : (( ( type ) ) -> ( ( prop ) )) , big_f : (( ( type ) ) -> ( ( prop ) )) , bigX : (( type )) , axiom1 : (( ~( ( ( big_f ) )-( ( bigX ) ) ) ) \/ ( ~( ( ( big_f ) )-( ( ( f ) )-( ( bigX ) ) ) ) )) , axiom0 : (( ( ( big_f ) )-( ( ( f ) )-( ( bigX ) ) ) ) \/ ( ( ( big_f ) )-( ( bigX ) ) )) ] , ~( ( ~( ( ( big_f ) )-( ( bigX ) ) ) ) \/ ( ( ( big_f ) )-( ( ( f ) )-( ( bigX ) ) ) ) ) , no , '../../TPTP-v7.3.0/Problems/SYN/SYN081-1.p').
checkTheorem(syn , 112 , [ type:set ,f : (( ( type ) ) -> ( ( prop ) )) , big_f : (( ( type ) ) -> ( ( prop ) )) , axiom0 : (pi(X:type,( ( ( ( big_f ) )-( ( bigX ) ) ) -> ( ~( ( ( big_f ) )-( ( ( f ) )-( ( bigX ) ) ) ) ) ) & ( ( ~( ( ( big_f ) )-( ( ( f ) )-( ( bigX ) ) ) ) ) -> ( ( ( big_f ) )-( ( bigX ) ) ) ))) ] , sigma(X:type,( ( ( big_f ) )-( ( bigX ) ) ) & ( ~( ( ( big_f ) )-( ( ( f ) )-( ( bigX ) ) ) ) )) , yes , '../../TPTP-v7.3.0/Problems/SYN/SYN081+1.p').
checkTheorem(syn , 113 , [ type:set ,g : (( ( type ) ) -> ( ( prop ) )) , bigX : (( ( type ) ) -> ( ( prop ) )) , b : (( type )) , bigY : (( type )) , big_f : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) , f : (( ( type ) ) -> ( ( prop ) )) , a : (( ( type ) ) -> ( ( prop ) )) ] , ( ~( ( ~( ( ~( ( ~( ( ~( ( ~( ( ~( ~( ( ( ( big_f ) )-( ( a ) )-( ( ( f ) )-( ( a ) ) ) ) \/ ( ( ~( ( ( big_f ) )-( ( bigY ) )-( ( b ) ) ) ) \/ ( ( ( big_f ) )-( ( bigY ) )-( ( ( f ) )-( ( a ) ) ) ) ) ) ) ) & ( ( ( ( big_f ) )-( ( a ) )-( ( ( f ) )-( ( a ) ) ) ) \/ ( ( ( big_f ) )-( ( a ) )-( ( b ) ) ) ) ) ) & ( ( ( ( big_f ) )-( ( ( g ) )-( ( bigX ) ) )-( ( bigX ) ) ) \/ ( ( ~( ( ( big_f ) )-( ( a ) )-( ( bigX ) ) ) ) \/ ( ( ~( ( ( big_f ) )-( ( bigY ) )-( ( b ) ) ) ) \/ ( ( ( big_f ) )-( ( bigY ) )-( ( ( f ) )-( ( a ) ) ) ) ) ) ) ) ) & ( ( ( ( big_f ) )-( ( ( g ) )-( ( bigX ) ) )-( ( bigX ) ) ) \/ ( ( ~( ( ( big_f ) )-( ( a ) )-( ( bigX ) ) ) ) \/ ( ( ( big_f ) )-( ( a ) )-( ( b ) ) ) ) ) ) ) & ( ( ( ( big_f ) )-( ( ( g ) )-( ( bigX ) ) )-( ( bigX ) ) ) \/ ( ( ~( ( ( big_f ) )-( ( a ) )-( ( bigX ) ) ) ) \/ ( ~( ( ( big_f ) )-( ( a ) )-( ( ( f ) )-( ( a ) ) ) ) ) ) ) ) ) & ( ( ~( ( ( big_f ) )-( ( ( g ) )-( ( bigX ) ) )-( ( bigX ) ) ) ) \/ ( ( ~( ( ( big_f ) )-( ( a ) )-( ( bigX ) ) ) ) \/ ( ( ~( ( ( big_f ) )-( ( bigY ) )-( ( b ) ) ) ) \/ ( ( ( big_f ) )-( ( bigY ) )-( ( ( f ) )-( ( a ) ) ) ) ) ) ) ) ) & ( ( ~( ( ( big_f ) )-( ( ( g ) )-( ( bigX ) ) )-( ( bigX ) ) ) ) \/ ( ( ~( ( ( big_f ) )-( ( a ) )-( ( bigX ) ) ) ) \/ ( ( ( big_f ) )-( ( a ) )-( ( b ) ) ) ) ) ) ) & ( ( ~( ( ( big_f ) )-( ( ( g ) )-( ( bigX ) ) )-( ( bigX ) ) ) ) \/ ( ( ~( ( ( big_f ) )-( ( a ) )-( ( bigX ) ) ) ) \/ ( ~( ( ( big_f ) )-( ( a ) )-( ( ( f ) )-( ( a ) ) ) ) ) ) ) , no , '../../TPTP-v7.3.0/Problems/SYN/SYN082-1.p').
