:- style_check(-singleton).

:-use_module(swi_alligator,[prove/2]).
:- op(500,xfx,:).
:- op(300,yfx,-).
:- op(400,xfy,=>).
:- op(400,xfy,&).
:- op(300,fy,~).
:- dynamic checktheorem/6.
writeResult(Logic,ID,Prediction,Gold,Fname) :-
format('~w&~w&~w&~w&~w~n', [Logic,ID,Prediction,Gold,Fname]).
evalyes(Logic,ID) :-
  checkTheorem(Logic,ID,Context,Theorem,Gold,Fname),
  ( prove(Context,_ : Theorem) -> writeResult(Logic,ID,yes,Gold,Fname)).
evalno(Logic,ID) :-
  checkTheorem(Logic,ID,Context,Theorem,Gold,Fname),
  ( prove(Context,_ : ( ~ (Theorem) ) ) -> writeResult(Logic,ID,no,Gold,Fname) ).
checkTheorem(syn , 372 , [ type:set ,g : (( ( type ) ) -> ( ( prop ) )) , y : (( ( type ) ) -> ( ( prop ) )) , f : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) , bigX : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) ] , ( ~( ( ~( ( ~( ( ~( ~( ( ( ( f ) )-( ( bigX ) )-( ( bigX ) ) ) \/ ( ( ( f ) )-( ( bigX ) )-( ( ( y ) )-( ( bigX ) ) ) ) ) ) ) & ( ( ( ( f ) )-( ( bigX ) )-( ( bigX ) ) ) \/ ( ( ( g ) )-( ( bigX ) ) ) ) ) ) & ( ( ~( ( ( f ) )-( ( ( y ) )-( ( bigX ) ) )-( ( ( y ) )-( ( bigX ) ) ) ) ) \/ ( ( ( f ) )-( ( bigX ) )-( ( ( y ) )-( ( bigX ) ) ) ) ) ) ) & ( ( ~( ( ( f ) )-( ( ( y ) )-( ( bigX ) ) )-( ( ( y ) )-( ( bigX ) ) ) ) ) \/ ( ( ( g ) )-( ( bigX ) ) ) ) ) ) & ( ~( ( ( g ) )-( ( ( y ) )-( ( bigX ) ) ) ) ) , no , '../../TPTP-v7.3.0/Problems/SYN/SYN325-1.p').
checkTheorem(syn , 373 , [ type:set ,big_g : (( ( type ) ) -> ( ( prop ) )) , big_f : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) ] , sigma(X:type,pi(Y:type,( ( ( ( ( big_f ) )-( ( bigX ) )-( ( bigX ) ) ) -> ( ( ( big_f ) )-( ( bigY ) )-( ( bigY ) ) ) ) -> ( ( ( ( big_f ) )-( ( bigX ) )-( ( bigY ) ) ) & ( ( ( big_g ) )-( ( bigX ) ) ) ) ) -> ( ( ( big_g ) )-( ( bigY ) ) ))) , yes , '../../TPTP-v7.3.0/Problems/SYN/SYN325+1.p').
checkTheorem(syn , 374 , [ type:set ,h : (( ( type ) ) -> ( ( prop ) )) , g : (( ( type ) ) -> ( ( prop ) )) , f : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) , z : (( ( type ) ) -> ( ( prop ) )) , y : (( ( type ) ) -> ( ( prop ) )) , bigX : (( ( type ) ) -> ( ( prop ) )) ] , ( ~( ( ~( ( ~( ( ~( ( ~( ( ~( ~( ( ( ( f ) )-( ( ( y ) )-( ( bigX ) ) )-( ( ( z ) )-( ( bigX ) ) ) ) \/ ( ( ( f ) )-( ( bigX ) )-( ( bigX ) ) ) ) ) ) & ( ( ( ( g ) )-( ( ( y ) )-( ( bigX ) ) ) ) \/ ( ( ( f ) )-( ( bigX ) )-( ( bigX ) ) ) ) ) ) & ( ( ~( ( ( h ) )-( ( bigX ) ) ) ) \/ ( ( ( f ) )-( ( bigX ) )-( ( bigX ) ) ) ) ) ) & ( ( ( ( f ) )-( ( ( z ) )-( ( bigX ) ) )-( ( bigX ) ) ) \/ ( ( ( h ) )-( ( ( z ) )-( ( bigX ) ) ) ) ) ) ) & ( ( ~( ( ( g ) )-( ( bigX ) ) ) ) \/ ( ( ( h ) )-( ( ( z ) )-( ( bigX ) ) ) ) ) ) ) & ( ( ( f ) )-( ( bigX ) )-( ( ( y ) )-( ( bigX ) ) ) ) ) ) & ( ~( ( ( f ) )-( ( ( z ) )-( ( bigX ) ) )-( ( ( z ) )-( ( bigX ) ) ) ) ) , no , '../../TPTP-v7.3.0/Problems/SYN/SYN326-1.p').
checkTheorem(syn , 375 , [ type:set ,big_h : (( ( type ) ) -> ( ( prop ) )) , big_g : (( ( type ) ) -> ( ( prop ) )) , big_f : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) ] , sigma(X:type,pi(Y:type,pi(Z:type,( ( ( ( ( big_f ) )-( ( bigY ) )-( ( bigZ ) ) ) -> ( ( ( ( big_g ) )-( ( bigY ) ) ) -> ( ( ( big_h ) )-( ( bigX ) ) ) ) ) -> ( ( ( big_f ) )-( ( bigX ) )-( ( bigX ) ) ) ) -> ( ( ( ( ( ( big_f ) )-( ( bigZ ) )-( ( bigX ) ) ) -> ( ( ( big_g ) )-( ( bigX ) ) ) ) -> ( ( ( big_h ) )-( ( bigZ ) ) ) ) -> ( ( ( ( big_f ) )-( ( bigX ) )-( ( bigY ) ) ) -> ( ( ( big_f ) )-( ( bigZ ) )-( ( bigZ ) ) ) ) )))) , yes , '../../TPTP-v7.3.0/Problems/SYN/SYN326+1.p').
checkTheorem(syn , 376 , [ type:set ,z : (( ( type ) ) -> ( ( prop ) )) , f : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) , a : (( type )) , bigY : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) ] , ( ~( ( ~( ( ~( ( ~( ( ~( ~( ( ( ( f ) )-( ( bigY ) )-( ( a ) ) ) \/ ( ( ( f ) )-( ( a ) )-( ( bigY ) ) ) ) ) ) & ( ( ( ( f ) )-( ( bigY ) )-( ( a ) ) ) \/ ( ~( ( ( f ) )-( ( a ) )-( ( ( z ) )-( ( bigY ) ) ) ) ) ) ) ) & ( ( ( ( f ) )-( ( a ) )-( ( ( z ) )-( ( bigY ) ) ) ) \/ ( ( ( f ) )-( ( a ) )-( ( bigY ) ) ) ) ) ) & ( ( ( ( f ) )-( ( a ) )-( ( ( z ) )-( ( bigY ) ) ) ) \/ ( ( ~( ( ( f ) )-( ( bigY ) )-( ( a ) ) ) ) \/ ( ~( ( ( f ) )-( ( ( z ) )-( ( bigY ) ) )-( ( bigY ) ) ) ) ) ) ) ) & ( ( ~( ( ( f ) )-( ( a ) )-( ( bigY ) ) ) ) \/ ( ~( ( ( f ) )-( ( a ) )-( ( ( z ) )-( ( bigY ) ) ) ) ) ) ) ) & ( ( ~( ( ( f ) )-( ( a ) )-( ( bigY ) ) ) ) \/ ( ( ~( ( ( f ) )-( ( bigY ) )-( ( a ) ) ) ) \/ ( ~( ( ( f ) )-( ( ( z ) )-( ( bigY ) ) )-( ( bigY ) ) ) ) ) ) , no , '../../TPTP-v7.3.0/Problems/SYN/SYN327-1.p').
checkTheorem(syn , 377 , [ type:set ,big_f : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) ] , pi(X:type,sigma(Y:type,pi(Z:type,( ( ( big_f ) )-( ( bigY ) )-( ( bigX ) ) ) -> ( ( ( ( ( big_f ) )-( ( bigX ) )-( ( bigZ ) ) ) -> ( ( ( big_f ) )-( ( bigX ) )-( ( bigY ) ) ) ) & ( ( ( ( big_f ) )-( ( bigX ) )-( ( bigY ) ) ) -> ( ( ~( ( ( big_f ) )-( ( bigX ) )-( ( bigZ ) ) ) ) -> ( ( ( ( big_f ) )-( ( bigY ) )-( ( bigX ) ) ) & ( ( ( big_f ) )-( ( bigZ ) )-( ( bigY ) ) ) ) ) ) )))) , yes , '../../TPTP-v7.3.0/Problems/SYN/SYN327+1.p').
