:- style_check(-singleton).

:-use_module(swi_alligator,[prove/2]).
:- op(500,xfx,:).
:- op(300,yfx,-).
:- op(400,xfy,=>).
:- op(400,xfy,&).
:- op(300,fy,~).
:- dynamic checktheorem/6.
writeResult(Logic,ID,Prediction,Gold,Fname) :-
format('~w&~w&~w&~w&~w~n', [Logic,ID,Prediction,Gold,Fname]).
evalyes(Logic,ID) :-
  checkTheorem(Logic,ID,Context,Theorem,Gold,Fname),
  ( prove(Context,_ : Theorem) -> writeResult(Logic,ID,yes,Gold,Fname)).
evalno(Logic,ID) :-
  checkTheorem(Logic,ID,Context,Theorem,Gold,Fname),
  ( prove(Context,_ : ( ~ (Theorem) ) ) -> writeResult(Logic,ID,no,Gold,Fname) ).
checkTheorem(syn , 360 , [ type:set ,z2 : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) , h : (( ( type ) ) -> ( ( prop ) )) , y : (( type )) , z1 : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) , g : (( ( type ) ) -> ( ( prop ) )) , bigX : (( type )) , f : (( ( type ) ) -> ( ( prop ) )) , bigY : (( ( type ) ) -> ( ( prop ) )) ] , ( ~( ( ~( ( ~( ( ~( ( ~( ( ~( ~( ( ( ( f ) )-( ( bigY ) ) ) \/ ( ( ( g ) )-( ( bigX ) ) ) ) ) ) & ( ( ( ( f ) )-( ( bigY ) ) ) \/ ( ~( ( ( f ) )-( ( ( z1 ) )-( ( bigX ) )-( ( bigY ) ) ) ) ) ) ) ) & ( ( ~( ( ( g ) )-( ( ( z1 ) )-( ( bigX ) )-( ( y ) ) ) ) ) \/ ( ( ( g ) )-( ( bigX ) ) ) ) ) ) & ( ( ~( ( ( g ) )-( ( ( z1 ) )-( ( bigX ) )-( ( y ) ) ) ) ) \/ ( ~( ( ( f ) )-( ( ( z1 ) )-( ( bigX ) )-( ( bigY ) ) ) ) ) ) ) ) & ( ( ~( ( ( f ) )-( ( bigX ) ) ) ) \/ ( ( ( h ) )-( ( bigX ) ) ) ) ) ) & ( ( ~( ( ( g ) )-( ( bigX ) ) ) ) \/ ( ( ( h ) )-( ( bigX ) ) ) ) ) ) & ( ~( ( ( h ) )-( ( ( z2 ) )-( ( bigX ) )-( ( bigY ) ) ) ) ) , no , '../../TPTP-v7.3.0/Problems/SYN/SYN319-1.p').
checkTheorem(syn , 361 , [ type:set ,big_h : (( ( type ) ) -> ( ( prop ) )) , big_g : (( ( type ) ) -> ( ( prop ) )) , big_f : (( ( type ) ) -> ( ( prop ) )) ] , sigma(X:type,sigma(Y:type,pi(Z1:type,pi(Z2:type,( ( ( ( ( big_f ) )-( ( bigY ) ) ) -> ( ( ( big_g ) )-( ( bigZ1 ) ) ) ) -> ( ( ( ( big_g ) )-( ( bigX ) ) ) & ( ~( ( ( big_f ) )-( ( bigZ1 ) ) ) ) ) ) -> ( ( ( ( ( ( big_f ) )-( ( bigX ) ) ) \/ ( ( ( big_g ) )-( ( bigX ) ) ) ) -> ( ( ( big_h ) )-( ( bigX ) ) ) ) -> ( ( ( ( big_h ) )-( ( bigZ2 ) ) ) & ( ( ( ( big_h ) )-( ( bigY ) ) ) -> ( ( ( ( ( big_f ) )-( ( bigZ2 ) ) ) \/ ( ( ( big_g ) )-( ( bigZ2 ) ) ) ) -> ( ( ( big_h ) )-( ( bigZ2 ) ) ) ) ) ) ))))) , yes , '../../TPTP-v7.3.0/Problems/SYN/SYN319+1.p').
checkTheorem(syn , 362 , [ type:set ,y2 : (( ( type ) ) -> ( ( prop ) )) , y1 : (( ( type ) ) -> ( ( prop ) )) , f : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) , a : (( ( type ) ) -> ( ( prop ) )) , bigX : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) ] , ( ~( ( ~( ~( ( ( ( f ) )-( ( bigX ) )-( ( a ) ) ) \/ ( ( ( f ) )-( ( a ) )-( ( ( y1 ) )-( ( bigX ) ) ) ) ) ) ) & ( ( ( f ) )-( ( ( y2 ) )-( ( bigX ) ) )-( ( a ) ) ) ) ) & ( ~( ( ( f ) )-( ( a ) )-( ( ( y2 ) )-( ( bigX ) ) ) ) ) , unknown , '../../TPTP-v7.3.0/Problems/SYN/SYN320-1.p').
checkTheorem(syn , 363 , [ type:set ,big_f : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) ] , sigma(Z:type,sigma(X:type,pi(Y1:type,pi(Y2:type,( ( ~( ( ( big_f ) )-( ( bigX ) )-( ( bigZ ) ) ) ) -> ( ( ( big_f ) )-( ( bigZ ) )-( ( bigY1 ) ) ) ) -> ( ( ( ( big_f ) )-( ( bigY2 ) )-( ( bigZ ) ) ) -> ( ( ( big_f ) )-( ( bigZ ) )-( ( bigY2 ) ) ) ))))) , no , '../../TPTP-v7.3.0/Problems/SYN/SYN320+1.p').
checkTheorem(syn , 364 , [ type:set ,d : (( type )) , b : (( type )) , g : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) , bigU : (( type )) , f : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) , bigZ : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) , a : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) ] , ( ~( ( ~( ( ~( ~( ( ~( ( ( f ) )-( ( a ) )-( ( bigZ ) ) ) ) \/ ( ( ( g ) )-( ( a ) )-( ( bigU ) ) ) ) ) ) & ( ( ~( ( ( g ) )-( ( bigU ) )-( ( bigU ) ) ) ) \/ ( ( ( f ) )-( ( bigU ) )-( ( b ) ) ) ) ) ) & ( ( ( ( f ) )-( ( a ) )-( ( b ) ) ) \/ ( ( ( g ) )-( ( a ) )-( ( bigU ) ) ) ) ) ) & ( ( ~( ( ( f ) )-( ( a ) )-( ( b ) ) ) ) \/ ( ~( ( ( g ) )-( ( a ) )-( ( d ) ) ) ) ) , no , '../../TPTP-v7.3.0/Problems/SYN/SYN321-1.p').
checkTheorem(syn , 365 , [ type:set ,big_g : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) , big_f : (( ( type ) ) -> ( ( ( type ) ) -> ( ( prop ) ) )) ] , sigma(X:type,sigma(Y:type,( ( sigma(Z:type,( ( big_f ) )-( ( bigX ) )-( ( bigZ ) )) ) -> ( pi(Z:type,( ( big_g ) )-( ( bigX ) )-( ( bigZ ) )) ) ) -> ( ( pi(Z:type,( ( ( big_g ) )-( ( bigZ ) )-( ( bigZ ) ) ) -> ( ( ( big_f ) )-( ( bigZ ) )-( ( bigY ) ) )) ) -> ( ( ( ( ( big_f ) )-( ( bigX ) )-( ( bigY ) ) ) -> ( pi(Z:type,( ( big_g ) )-( ( bigX ) )-( ( bigZ ) )) ) ) & ( ( pi(Z:type,( ( big_g ) )-( ( bigX ) )-( ( bigZ ) )) ) -> ( ( ( big_f ) )-( ( bigX ) )-( ( bigY ) ) ) ) ) ))) , yes , '../../TPTP-v7.3.0/Problems/SYN/SYN321+1.p').
